In [1]:

# =============================================================================
# CELL 1 – IMPORTS, DARK THEME, AND HELPERS
# =============================================================================

import importlib
import sys
import json
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display, HTML, Markdown

# -------------------- Dark Theme --------------------
display(HTML("""
<style>
    body, .jp-Notebook, .jp-OutputArea-output, .jp-RenderedHTMLCommon {
        background-color: #1e1e1e !important;
        color: #d4d4d4 !important;
    }
    h2, h3, h4 {
        color: #4fc3f7 !important;
        border-bottom: 2px solid #3498db !important;
        padding-bottom: 4px;
    }
    b, strong { color: #f48fb1 !important; }
    .highlight {
        background-color: #2d2d2d !important;
        padding: 10px;
        border-left: 4px solid #3498db;
        margin: 4px 0;
        color: #d4d4d4;
    }
    code {
        background-color: #333 !important;
        color: #ffcc80 !important;
        padding: 2px 4px;
        border-radius: 4px;
    }
    .dataframe {
        background-color: #2d2d2d !important;
        color: #d4d4d4 !important;
    }
</style>
"""))

# -------------------- Verbosity Flags --------------------
SHOW_VERBOSE = True
SHOW_INFO = True
SHOW_CRITICAL = True
SHOW_DEBUG = True
# For demonstration, we keep them False to reduce output; you can set True as needed.


# -------------------- Import Extraction Module --------------------
import Extraction6_new as Extraction6
importlib.reload(Extraction6)

# -------------------- Helper Functions --------------------
def display_title(title: str):
    display(HTML(f"<h2>{title}</h2>"))

def display_info(message: str):
    display(HTML(f"<div class='highlight'>{message}</div>"))
    

def discover_extractions(exp_root: Path) -> pd.DataFrame:
    rows = []
    for f in exp_root.rglob("extraction.json"):
        parts = f.relative_to(exp_root).parts
        try:
            models_idx = parts.index("models")
            datasets_idx = parts.index("datasets")
            model = "/".join(parts[models_idx+1:datasets_idx])
            dataset = parts[datasets_idx+1]
            rows.append({"model": model, "dataset": dataset, "path": str(f)})
        except ValueError:
            rows.append({"model": None, "dataset": None, "path": str(f)})
    return pd.DataFrame(rows)

def load_experiment_results(exp_root: Path) -> pd.DataFrame:
    """
    Load all extraction results from the experiment directory, inferring model and
    dataset names from the file path if they are missing in the JSON.
    """
    records = []
    exp_root = Path(exp_root)
    if not exp_root.exists():
        return pd.DataFrame()

    for meta_file in exp_root.rglob("extraction.json"):
        try:
            with open(meta_file, "r") as f:
                meta = json.load(f)

            # Extract model and dataset from path (most reliable)
            parts = meta_file.relative_to(exp_root).parts
            try:
                models_idx = parts.index("models")
                datasets_idx = parts.index("datasets")
                model = "/".join(parts[models_idx+1:datasets_idx])
                dataset = parts[datasets_idx+1]
            except ValueError:
                # Fallback to metadata
                model = meta.get("model", {}).get("name")
                dataset = meta.get("dataset", {}).get("name")

            record = {
                "experiment_id": meta.get("experiment_id"),
                "model": model,
                "dataset": dataset,
                "status": meta.get("status"),
                "completed_samples": meta.get("performance", {}).get("completed_samples"),
                "total_samples": meta.get("dataset", {}).get("samples"),
                "batch_size": meta.get("extraction", {}).get("batch_size"),
                "pooling": meta.get("extraction", {}).get("pooling"),
                "max_length": meta.get("extraction", {}).get("max_length"),
                "samples_per_second": meta.get("performance", {}).get("samples_per_second"),
                "tokens_per_second": meta.get("performance", {}).get("tokens_per_second"),
                "elapsed_seconds": meta.get("performance", {}).get("elapsed_seconds"),
                "error": None,
                "text_column": meta.get("dataset", {}).get("text_column"),
                "label_column": meta.get("dataset", {}).get("labels", {}).get("label_column"),
            }
            records.append(record)
        except Exception:
            continue

    return pd.DataFrame(records)

print("Environment ready. Dark theme applied.")

Environment ready. Dark theme applied.

In [2]:
# =============================================================================
# CELL 2 – LOAD AND INSPECT DATASETS
# =============================================================================

from Get_Go_Emo import get_go
from Get_Isear import get_isr

goEmo = get_go()
isear = get_isr()

DATASETS = {
    "goEmo": goEmo,
    "ISEAR": isear,
}

for name, df in DATASETS.items():
    display_title(f"Dataset: {name}")
    display_info(f"Shape: {df.shape}")
    display(df.head(2))
    text_col = Extraction6.detect_text_column(df, show_verbose=False)
    label_cols = [c for c in df.columns if c.lower() in ("labels", "label", "emotion", "target")]
    label_col = label_cols[0] if label_cols else None
    display_info(f"Text column: <b>{text_col}</b><br>Label column: <b>{label_col or 'None'}</b><br>Samples: <b>{len(df):,}</b>")

display_title("Unified ID Scheme")
display_info("""
Each sample is assigned a unique integer ID (0..N-1) matching its row index.
This ID links:
• Input text (original DataFrame index)
• Hidden state vector (row in hidden_states.npy)
• Label (row in labels.npy)
No shuffling occurs, guaranteeing one‑to‑one mapping.
""")

  labels                                         clean_text
0   [27]  my favourite food is anything i didnt have to ...
1   [27]  now if he does off himself, everyone will thin...

                                          clean_text  labels
0  during the period of falling in love each time...       1
1          when i was involved in a traffic accident       2

In [3]:
# =============================================================================
# CELL 3 – RUN MODEL MATRIX (ENHANCED, WITH SAFEGUARDS)
# =============================================================================

# This call will automatically resume from existing completions.
# If interrupted, simply re-run this cell to continue.
results = Extraction6.run_model_matrix(
    datasets=DATASETS,
    groups=None,                     # all 25 models
    base_output="/Volumes/Amirali/hidden_states",
    pooling="mean",
    max_length=512,
    use_half_precision=True,
    auto_batch_size=False,
    flush_every_batches=8,
    continue_on_model_error=True,
    show_verbose=SHOW_VERBOSE,
    show_info=SHOW_INFO,
    show_critical=SHOW_CRITICAL,
    show_debug=SHOW_DEBUG,
)

print(f"Returned result records: {len(results)}")

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL MATRIX                                                                         ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Requested experiment : baseline_v5_001
  Transformers         : 4.47.1
  PyTorch              : 2.2.2
  Models               : 25
  Datasets             : 2
  Runtime batch tuning : DISABLED
  Output root          : /Volumes/Amirali/hidden_states
01. [01_encoders] BERT         0.11B  google-bert/bert-base-uncased
02. [01_encoders] DistilBERT   0.066B  distilbert/distilbert-base-uncased
03. [01_encoders] RoBERTa      0.125B  FacebookAI/roberta-base
04. [01_encoders] ELECTRA      0.014B  google/electra-small-discriminator
05. [01_encoders] DeBERTa      0.14B  microsoft/deberta-v3-small
06. [02_early_decoders] GPT          0.124B  gpt2
07. [02_early_decoders] GPT-Neo      0.125B  EleutherAI/gpt-neo-125m
08. [02_early_decoders] OPT          0.125B  facebook/opt-125m
09. [03_tiny_modern] SmolLM2      0.135B  HuggingFaceTB/SmolLM2-135M
10. [03_tiny_modern] SmolLM2      0.36B  HuggingFaceTB/SmolLM2-360M
11. [03_tiny_modern] Gemma        0.27B  google/gemma-3-270m
12. [03_tiny_modern] Qwen         0.5B  Qwen/Qwen2-0.5B
13. [03_tiny_modern] Qwen         0.5B  Qwen/Qwen2.5-0.5B
14. [03_tiny_modern] Qwen         0.6B  Qwen/Qwen3-0.6B-Base
15. [04_qwen_scaling] Qwen         1.5B  Qwen/Qwen2-1.5B
16. [04_qwen_scaling] Qwen         1.54B  Qwen/Qwen2.5-1.5B
17. [04_qwen_scaling] Qwen         3.09B  Qwen/Qwen2.5-3B
18. [04_qwen_scaling] Qwen         1.7B  Qwen/Qwen3-1.7B-Base
19. [05_independent_small] SmolLM2      1.7B  HuggingFaceTB/SmolLM2-1.7B
20. [05_independent_small] TinyLlama    1.1B  TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
21. [05_independent_small] Gemma        1B  google/gemma-3-1b-pt
22. [05_independent_small] Llama        1B  meta-llama/Llama-3.2-1B
23. [06_stretch] Qwen         4B  Qwen/Qwen3-4B-Base
24. [06_stretch] Llama        3B  meta-llama/Llama-3.2-3B
25. [06_stretch] Gemma        4B  google/gemma-3-4b-pt

↻ EXISTING EXPERIMENT DETECTED
  Experiment ID        : baseline_v5_001
  Saved hyperparameter : d90449246241487f
  Manifest             : /Volumes/Amirali/hidden_states/experiments/baseline_v5_001/run_manifest.json
  The saved experiment configuration is authoritative.
  Current-call overrides are ignored for this resume.
  Requested overrides  : {'pooling': 'mean', 'max_length': 512, 'use_half_precision': True, 'flush_every_batches': 8}


╔══════════════════════════════════════════════════════════════════════════════════════╗
║ HIDDEN STATE EXTRACTION EXPERIMENT                                                   ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Experiment ID       : baseline_v5_001
  Hyperparameter hash : d90449246241487f
  Device              : cpu
  Models requested    : 25
  Datasets            : 2
  Pooling             : mean
  Max sequence length : 512
  Runtime batch tuning: DISABLED
  Existing experiment : YES
  Output root         : /Volumes/Amirali/hidden_states/experiments/baseline_v5_001
  Transformers        : 4.47.1
  PyTorch             : 2.2.2

────────────────────────────────────────────────────────────────────────────────────────
SYSTEM / STORAGE REPORT
  Architecture        : x86_64
  Logical CPUs        : 8
  PyTorch threads     : 4
  PyTorch interop     : 8
  Python              : 3.12.0
  RAM total           : 8.00 GiB
  RAM available       : 2.28 GiB
  Adaptive reserve    : 0.50 GiB
  External free       : 1744.87 GiB
  System fingerprint  : d45c07bfe59422f0

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 1/25 :: google-bert/bert-base-uncased                                          ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : BERT
  Generation          : 2018
  Parameters          : 0.11B
  Architecture        : encoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for goEmo
  Repaired ISEAR: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 2/25 :: distilbert/distilbert-base-uncased                                     ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : DistilBERT
  Generation          : 2019
  Parameters          : 0.066B
  Architecture        : encoder
  Training status     : pretrained_distilled
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for goEmo
  Repaired ISEAR: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 3/25 :: FacebookAI/roberta-base                                                ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : RoBERTa
  Generation          : 2019
  Parameters          : 0.125B
  Architecture        : encoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for goEmo
  Repaired ISEAR: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 4/25 :: google/electra-small-discriminator                                     ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : ELECTRA
  Generation          : 2020
  Parameters          : 0.014B
  Architecture        : encoder
  Training status     : pretrained_discriminator
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for goEmo
  Repaired ISEAR: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 5/25 :: microsoft/deberta-v3-small                                             ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : DeBERTa
  Generation          : 2021
  Parameters          : 0.14B
  Architecture        : encoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for goEmo
  Repaired ISEAR: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 6/25 :: gpt2                                                                   ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : GPT
  Generation          : 2019
  Parameters          : 0.124B
  Architecture        : decoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for goEmo
  Repaired ISEAR: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 7/25 :: EleutherAI/gpt-neo-125m                                                ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : GPT-Neo
  Generation          : 2021
  Parameters          : 0.125B
  Architecture        : decoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for goEmo
  Repaired ISEAR: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 8/25 :: facebook/opt-125m                                                      ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : OPT
  Generation          : 2022
  Parameters          : 0.125B
  Architecture        : decoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for goEmo
  Repaired ISEAR: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 9/25 :: HuggingFaceTB/SmolLM2-135M                                             ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : SmolLM2
  Generation          : 2024
  Parameters          : 0.135B
  Architecture        : decoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: labels.npy already compatible, updated extraction.json with v2 fields
  Updated metadata for goEmo
  Repaired ISEAR: labels.npy already compatible
  HF root         : /Volumes/Amirali/hidden_states/huggingface_cache ✓
  Hub cache       : /Volumes/Amirali/hidden_states/huggingface_cache/hub ✓
  Xet cache       : /Volumes/Amirali/hidden_states/huggingface_cache/xet ✓
  Assets cache    : /Volumes/Amirali/hidden_states/huggingface_cache/assets ✓

→ Preparing Hugging Face model: HuggingFaceTB/SmolLM2-135M
  Pinned revision      : 93efa2f097d58c2a74874c7e644dbc9b0cee75a2
  Preparation attempt 1/4
  DOWNLOAD DIAGNOSTICS
    Revision             : 93efa2f097d58c2a74874c7e644dbc9b0cee75a2
    Cache                : /Volumes/Amirali/hidden_states/huggingface_cache/hub
    Workers              : 4
    ETag timeout         : 20.0s
    Allow patterns       : ['config.json', 'generation_config.json', 'tokenizer_config.json', 'tokenizer.json', 'special_tokens_map.json', 'added_tokens.json', 'vocab.json', 'merges.txt', 'spiece.model', 'spm.model', 'sentencepiece.bpe.model', 'tokenizer.model', 'vocab.txt', 'LICENSE*', 'README.md', '*.json', '*.safetensors']
    Ignore patterns      : ['*.h5', '*.msgpack', '*.ot', 'tf_model.*', 'flax_model.*', 'rust_model.ot', '*.onnx', '*.gguf', '*.ggml', '*.bin']

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

  ✓ Snapshot ready
    Attempt time        : 1.36s
    Total preparation   : 1.40s
    Checkpoint size     : 0.251 GiB
    Snapshot            : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--HuggingFaceTB--SmolLM2-135M/snapshots/93efa2f097d58c2a74874c7e644dbc9b0cee75a2

────────────────────────────────────────────────────────────────────────────────────────
MODEL PREFLIGHT
────────────────────────────────────────────────────────────────────────────────────────
  model                             : HuggingFaceTB/SmolLM2-135M
  model_type                        : llama
  architecture                      : decoder
  dtype                             : torch.float32
  device                            : cpu
  layers                            : 30
  hidden_size                       : 576
  hidden_states                     : 31
  max_length                        : 512
  checkpoint                        : {'active_bytes': 269064648, 'active_gb': 0.25058598071336746, 'inventory': {'safetensors': [{'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--HuggingFaceTB--SmolLM2-135M/snapshots/93efa2f097d58c2a74874c7e644dbc9b0cee75a2/._model.safetensors', 'filename': '._model.safetensors', 'size_bytes': 4096, 'size_gb': 3.814697265625e-06}, {'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--HuggingFaceTB--SmolLM2-135M/snapshots/93efa2f097d58c2a74874c7e644dbc9b0cee75a2/model.safetensors', 'filename': 'model.safetensors', 'size_bytes': 269060552, 'size_gb': 0.25058216601610184}], 'pytorch_bin': [], 'index_files': [], 'safetensors_total_bytes': 269064648, 'pytorch_bin_total_bytes': 0}}
  estimated_loaded_weight_gb        : 0.5011719614267349
  estimated_model_load_peak_gb      : 0.6014063537120818
  memory                            : {'total_gb': 8.0, 'available_gb': 2.283000946044922, 'used_gb': 4.484245300292969, 'reserve_gb': 0.5, 'safe_total_memory_gb': 6.4}
  status                            : ok
  ✓ Tokenizer loaded in 0.47s Mode=fast
  TOKENIZER DIAGNOSTICS
    class              : GPT2TokenizerFast
    vocab size         : 49152
    pad token          : '<|endoftext|>'
    pad source         : eos
    attempts           : [{"mode": "auto_fast", "success": true, "error_type": null, "error": null}]

MODEL LOAD ATTEMPT
  Attempt              : 1/2
  Path                 : primary
  Model                : HuggingFaceTB/SmolLM2-135M
  Snapshot             : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--HuggingFaceTB--SmolLM2-135M/snapshots/93efa2f097d58c2a74874c7e644dbc9b0cee75a2
  dtype                : torch.float32
  device               : cpu
  SDPA                 : True
  low_cpu_mem_usage    : True
  LOADING RESULT
    Missing keys        : 0
    Non-core missing    : 0
    Core missing        : 0
    Unexpected keys     : 0
    Mismatched keys     : 0
    Meta tensors        : 0
    Core meta           : 0
    Fatal discrepancy   : False
  FULL LOADING DIAGNOSTICS
{
  "missing_keys": [],
  "unexpected_keys": [],
  "mismatched_keys": [],
  "non_core_missing_keys": [],
  "core_missing_keys": [],
  "all_meta_tensors": [],
  "non_core_meta_tensors": [],
  "core_meta_tensors": [],
  "has_meta_tensors": false,
  "fatal": false
}

✓ MODEL READY
  Load/probe time       : 12.02s
  Backend               : sdpa
  Model device          : cpu
  Hidden states         : 31
  Hidden size           : 576
  Text-column resolver: exact candidate 'clean_text'

────────────────────────────────────────────────────────────────────────────────────────
DATASET goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Text column         : clean_text
  Samples             : 54,263
  Dataset fingerprint : 6302b3ba58f9886999c7
  Hidden layers       : 31
  Hidden size         : 576
  Output size est.    : 3.61 GiB
  Pooling             : mean
  Max length          : 512
  FROZEN batch        : 64
  Device              : cpu
  Runtime diagnostics : /Volumes/Amirali/hidden_states/experiments/baseline_v5_001/models/HuggingFaceTB/SmolLM2-135M/datasets/goEmo/metadata/runtime_state.json
✓ DATASET ALREADY COMPLETE (metadata updated): goEmo
  Text-column resolver: exact candidate 'clean_text'

────────────────────────────────────────────────────────────────────────────────────────
DATASET ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Text column         : clean_text
  Samples             : 7,666
  Dataset fingerprint : c96aebef9c5742e9b896
  Hidden layers       : 31
  Hidden size         : 576
  Output size est.    : 0.51 GiB
  Pooling             : mean
  Max length          : 512
  FROZEN batch        : 64
  Device              : cpu
  Runtime diagnostics : /Volumes/Amirali/hidden_states/experiments/baseline_v5_001/models/HuggingFaceTB/SmolLM2-135M/datasets/ISEAR/metadata/runtime_state.json
  Existing progress   : 0/7,666 (0.00%)

ISEAR:   0%|          | 0/7666 [00:00<?, ?sample/s]

[start] starting at absolute sample 0
[batch] 0:64 processed
[batch] 64:128 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 128/7,666 (1.67%)
  Newly computed       : 128
  Wall time            : 21.89s
  Throughput           : 5.85 samples/s
  ETA                  : 21m 29.0s
  Current stage        : measurement

  LAST BATCH
    Range              : 64:128
    New samples        : 64
    Total              : 13.40s
    Forward            : 12.67s
    Tokenization       : 0.02s
    Input transfer     : 0.00s
    Pooling            : 0.13s
    Conversion         : 0.00s
    Memmap write       : 0.09s
    Flush              : 0.10s
    Sequence length    : 59
    Tokens             : 1283
    Token throughput   : 95.73 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 10.910s
    Median batch       : 10.910s
    P95 batch          : 13.402s
    Max batch          : 13.402s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.65 GiB
    Process RSS        : 1.0711402893066406
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.65 GiB
    External free      : 1744.86 GiB
    Successful batches : 2
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 128:192 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 192/7,666 (2.50%)
  Newly computed       : 192
  Wall time            : 37.32s
  Throughput           : 5.14 samples/s
  ETA                  : 24m 12.9s
  Current stage        : measurement

  LAST BATCH
    Range              : 128:192
    New samples        : 64
    Total              : 15.41s
    Forward            : 13.56s
    Tokenization       : 0.02s
    Input transfer     : 0.00s
    Pooling            : 0.55s
    Conversion         : 0.00s
    Memmap write       : 0.36s
    Flush              : 0.08s
    Sequence length    : 63
    Tokens             : 1438
    Token throughput   : 93.34 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 12.409s
    Median batch       : 13.402s
    P95 batch          : 15.407s
    Max batch          : 15.407s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.52 GiB
    Process RSS        : 1.0457382202148438
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.52 GiB
    External free      : 1744.86 GiB
    Successful batches : 3
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 192:256 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 256/7,666 (3.34%)
  Newly computed       : 256
  Wall time            : 54.07s
  Throughput           : 4.73 samples/s
  ETA                  : 26m 04.9s
  Current stage        : measurement

  LAST BATCH
    Range              : 192:256
    New samples        : 64
    Total              : 16.72s
    Forward            : 14.95s
    Tokenization       : 0.02s
    Input transfer     : 0.00s
    Pooling            : 0.35s
    Conversion         : 0.00s
    Memmap write       : 0.06s
    Flush              : 0.13s
    Sequence length    : 78
    Tokens             : 1219
    Token throughput   : 72.91 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 13.486s
    Median batch       : 14.404s
    P95 batch          : 16.718s
    Max batch          : 16.718s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.58 GiB
    Process RSS        : 0.9687232971191406
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.52 GiB
    External free      : 1744.85 GiB
    Successful batches : 4
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 256:320 processed
[batch] 320:384 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 384/7,666 (5.01%)
  Newly computed       : 384
  Wall time            : 1m 19.3s
  Throughput           : 4.84 samples/s
  ETA                  : 25m 04.5s
  Current stage        : measurement

  LAST BATCH
    Range              : 320:384
    New samples        : 64
    Total              : 15.30s
    Forward            : 14.58s
    Tokenization       : 0.02s
    Input transfer     : 0.00s
    Pooling            : 0.11s
    Conversion         : 0.00s
    Memmap write       : 0.10s
    Flush              : 0.09s
    Sequence length    : 64
    Tokens             : 1260
    Token throughput   : 82.34 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 13.195s
    Median batch       : 14.352s
    P95 batch          : 16.718s
    Max batch          : 16.718s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.40 GiB
    Process RSS        : 0.8736763000488281
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.40 GiB
    External free      : 1744.85 GiB
    Successful batches : 6
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 384:448 processed
[batch] 448:512 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 512/7,666 (6.68%)
  Newly computed       : 512
  Wall time            : 1m 47.3s
  Throughput           : 4.77 samples/s
  ETA                  : 24m 59.9s
  Current stage        : measurement

  LAST BATCH
    Range              : 448:512
    New samples        : 64
    Total              : 16.04s
    Forward            : 14.94s
    Tokenization       : 0.03s
    Input transfer     : 0.00s
    Pooling            : 0.15s
    Conversion         : 0.00s
    Memmap write       : 0.10s
    Flush              : 0.10s
    Sequence length    : 65
    Tokens             : 1246
    Token throughput   : 77.67 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 13.392s
    Median batch       : 14.352s
    P95 batch          : 16.718s
    Max batch          : 16.718s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.21 GiB
    Process RSS        : 0.7609634399414062
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.21 GiB
    External free      : 1744.85 GiB
    Successful batches : 8
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 512:576 processed
[batch] 576:640 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 640/7,666 (8.35%)
  Newly computed       : 640
  Wall time            : 2m 13.7s
  Throughput           : 4.79 samples/s
  ETA                  : 24m 27.5s
  Current stage        : measurement

  LAST BATCH
    Range              : 576:640
    New samples        : 64
    Total              : 17.76s
    Forward            : 16.77s
    Tokenization       : 0.03s
    Input transfer     : 0.00s
    Pooling            : 0.15s
    Conversion         : 0.00s
    Memmap write       : 0.10s
    Flush              : 0.11s
    Sequence length    : 76
    Tokens             : 1692
    Token throughput   : 95.25 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 13.341s
    Median batch       : 14.352s
    P95 batch          : 17.765s
    Max batch          : 17.765s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.42 GiB
    Process RSS        : 0.930206298828125
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.21 GiB
    External free      : 1744.85 GiB
    Successful batches : 10
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 640:704 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 704/7,666 (9.18%)
  Newly computed       : 704
  Wall time            : 2m 29.2s
  Throughput           : 4.72 samples/s
  ETA                  : 24m 35.8s
  Current stage        : measurement

  LAST BATCH
    Range              : 640:704
    New samples        : 64
    Total              : 15.51s
    Forward            : 14.38s
    Tokenization       : 0.02s
    Input transfer     : 0.00s
    Pooling            : 0.22s
    Conversion         : 0.00s
    Memmap write       : 0.16s
    Flush              : 0.10s
    Sequence length    : 59
    Tokens             : 1025
    Token throughput   : 66.08 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 13.539s
    Median batch       : 15.302s
    P95 batch          : 17.765s
    Max batch          : 17.765s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.59 GiB
    Process RSS        : 0.821533203125
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.21 GiB
    External free      : 1744.85 GiB
    Successful batches : 11
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 704:768 processed
[batch] 768:832 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 832/7,666 (10.85%)
  Newly computed       : 832
  Wall time            : 2m 53.3s
  Throughput           : 4.80 samples/s
  ETA                  : 23m 43.9s
  Current stage        : measurement

  LAST BATCH
    Range              : 768:832
    New samples        : 64
    Total              : 13.00s
    Forward            : 12.20s
    Tokenization       : 0.02s
    Input transfer     : 0.00s
    Pooling            : 0.13s
    Conversion         : 0.00s
    Memmap write       : 0.11s
    Flush              : 0.11s
    Sequence length    : 50
    Tokens             : 983
    Token throughput   : 75.63 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 13.306s
    Median batch       : 13.402s
    P95 batch          : 17.765s
    Max batch          : 17.765s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.49 GiB
    Process RSS        : 0.7937774658203125
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.21 GiB
    External free      : 1744.85 GiB
    Successful batches : 13
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 832:896 processed
[batch] 896:960 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 960/7,666 (12.52%)
  Newly computed       : 960
  Wall time            : 3m 13.3s
  Throughput           : 4.97 samples/s
  ETA                  : 22m 30.5s
  Current stage        : measurement

  LAST BATCH
    Range              : 896:960
    New samples        : 64
    Total              : 12.99s
    Forward            : 12.01s
    Tokenization       : 0.02s
    Input transfer     : 0.00s
    Pooling            : 0.14s
    Conversion         : 0.00s
    Memmap write       : 0.39s
    Flush              : 0.04s
    Sequence length    : 49
    Tokens             : 995
    Token throughput   : 76.59 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 12.860s
    Median batch       : 12.998s
    P95 batch          : 17.765s
    Max batch          : 17.765s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.62 GiB
    Process RSS        : 0.73382568359375
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.21 GiB
    External free      : 1744.85 GiB
    Successful batches : 15
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 960:1024 processed
[batch] 1024:1088 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 1,088/7,666 (14.19%)
  Newly computed       : 1,088
  Wall time            : 3m 47.0s
  Throughput           : 4.79 samples/s
  ETA                  : 22m 52.6s
  Current stage        : measurement

  LAST BATCH
    Range              : 1024:1088
    New samples        : 64
    Total              : 21.81s
    Forward            : 20.57s
    Tokenization       : 0.02s
    Input transfer     : 0.00s
    Pooling            : 0.20s
    Conversion         : 0.00s
    Memmap write       : 0.10s
    Flush              : 0.10s
    Sequence length    : 74
    Tokens             : 1528
    Token throughput   : 70.05 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 13.324s
    Median batch       : 12.998s
    P95 batch          : 21.813s
    Max batch          : 21.813s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.22 GiB
    Process RSS        : 0.7708778381347656
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.21 GiB
    External free      : 1744.84 GiB
    Successful batches : 17
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 1088:1152 processed
[batch] 1152:1216 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 1,216/7,666 (15.86%)
  Newly computed       : 1,216
  Wall time            : 4m 20.2s
  Throughput           : 4.67 samples/s
  ETA                  : 23m 00.0s
  Current stage        : measurement

  LAST BATCH
    Range              : 1152:1216
    New samples        : 64
    Total              : 20.01s
    Forward            : 18.58s
    Tokenization       : 0.03s
    Input transfer     : 0.00s
    Pooling            : 0.19s
    Conversion         : 0.00s
    Memmap write       : 0.09s
    Flush              : 0.20s
    Sequence length    : 82
    Tokens             : 1450
    Token throughput   : 72.47 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 13.664s
    Median batch       : 13.097s
    P95 batch          : 21.813s
    Max batch          : 21.813s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.45 GiB
    Process RSS        : 0.8711585998535156
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.21 GiB
    External free      : 1744.83 GiB
    Successful batches : 19
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 1216:1280 processed
[batch] 1280:1344 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 1,344/7,666 (17.53%)
  Newly computed       : 1,344
  Wall time            : 4m 43.0s
  Throughput           : 4.75 samples/s
  ETA                  : 22m 11.0s
  Current stage        : measurement

  LAST BATCH
    Range              : 1280:1344
    New samples        : 64
    Total              : 12.22s
    Forward            : 11.50s
    Tokenization       : 0.04s
    Input transfer     : 0.00s
    Pooling            : 0.11s
    Conversion         : 0.00s
    Memmap write       : 0.10s
    Flush              : 0.11s
    Sequence length    : 59
    Tokens             : 1835
    Token throughput   : 150.13 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 13.694s
    Median batch       : 13.047s
    P95 batch          : 20.008s
    Max batch          : 21.813s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.62 GiB
    Process RSS        : 0.8666610717773438
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.21 GiB
    External free      : 1744.83 GiB
    Successful batches : 21
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 1344:1408 processed
[batch] 1408:1472 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 1,472/7,666 (19.20%)
  Newly computed       : 1,472
  Wall time            : 5m 06.1s
  Throughput           : 4.81 samples/s
  ETA                  : 21m 27.9s
  Current stage        : measurement

  LAST BATCH
    Range              : 1408:1472
    New samples        : 64
    Total              : 13.12s
    Forward            : 12.24s
    Tokenization       : 0.04s
    Input transfer     : 0.00s
    Pooling            : 0.14s
    Conversion         : 0.00s
    Memmap write       : 0.12s
    Flush              : 0.15s
    Sequence length    : 80
    Tokens             : 1983
    Token throughput   : 151.20 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 13.406s
    Median batch       : 12.994s
    P95 batch          : 20.008s
    Max batch          : 21.813s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.49 GiB
    Process RSS        : 1.0332679748535156
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.21 GiB
    External free      : 1744.82 GiB
    Successful batches : 23
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 1472:1536 processed
[batch] 1536:1600 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 1,600/7,666 (20.87%)
  Newly computed       : 1,600
  Wall time            : 5m 26.5s
  Throughput           : 4.90 samples/s
  ETA                  : 20m 37.8s

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

  ✓ Snapshot ready
    Attempt time        : 1.01s
    Total preparation   : 1.01s
    Checkpoint size     : 0.920 GiB
    Snapshot            : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--Qwen--Qwen2.5-0.5B/snapshots/060db6499f32faf8b98477b0a26969ef7d8b9987

────────────────────────────────────────────────────────────────────────────────────────
MODEL PREFLIGHT
────────────────────────────────────────────────────────────────────────────────────────
  model                             : Qwen/Qwen2.5-0.5B
  model_type                        : qwen2
  architecture                      : decoder
  dtype                             : torch.float32
  device                            : cpu
  layers                            : 24
  hidden_size                       : 896
  hidden_states                     : 25
  max_length                        : 512
  checkpoint                        : {'active_bytes': 988097824, 'active_gb': 0.920237809419632, 'inventory': {'safetensors': [{'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--Qwen--Qwen2.5-0.5B/snapshots/060db6499f32faf8b98477b0a26969ef7d8b9987/model.safetensors', 'filename': 'model.safetensors', 'size_bytes': 988097824, 'size_gb': 0.920237809419632}], 'pytorch_bin': [], 'index_files': [], 'safetensors_total_bytes': 988097824, 'pytorch_bin_total_bytes': 0}}
  estimated_loaded_weight_gb        : 1.840475618839264
  estimated_model_load_peak_gb      : 2.2085707426071166
  memory                            : {'total_gb': 8.0, 'available_gb': 2.8763504028320312, 'used_gb': 3.94708251953125, 'reserve_gb': 0.5752700805664063, 'safe_total_memory_gb': 6.4}
  status                            : ok
  ✓ Tokenizer loaded in 1.13s Mode=fast
  TOKENIZER DIAGNOSTICS
    class              : Qwen2TokenizerFast
    vocab size         : 151665
    pad token          : '<|endoftext|>'
    pad source         : checkpoint-defined
    attempts           : [{"mode": "auto_fast", "success": true, "error_type": null, "error": null}]

MODEL LOAD ATTEMPT
  Attempt              : 1/2
  Path                 : primary
  Model                : Qwen/Qwen2.5-0.5B
  Snapshot             : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--Qwen--Qwen2.5-0.5B/snapshots/060db6499f32faf8b98477b0a26969ef7d8b9987
  dtype                : torch.float32
  device               : cpu
  SDPA                 : True
  low_cpu_mem_usage    : True
  LOADING RESULT
    Missing keys        : 0
    Non-core missing    : 0
    Core missing        : 0
    Unexpected keys     : 0
    Mismatched keys     : 0
    Meta tensors        : 0
    Core meta           : 0
    Fatal discrepancy   : False
  FULL LOADING DIAGNOSTICS
{
  "missing_keys": [],
  "unexpected_keys": [],
  "mismatched_keys": [],
  "non_core_missing_keys": [],
  "core_missing_keys": [],
  "all_meta_tensors": [],
  "non_core_meta_tensors": [],
  "core_meta_tensors": [],
  "has_meta_tensors": false,
  "fatal": false
}

✓ MODEL READY
  Load/probe time       : 24.32s
  Backend               : sdpa
  Model device          : cpu
  Hidden states         : 25
  Hidden size           : 896
  Text-column resolver: exact candidate 'clean_text'

────────────────────────────────────────────────────────────────────────────────────────
DATASET goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Text column         : clean_text
  Samples             : 54,263
  Dataset fingerprint : 6302b3ba58f9886999c7
  Hidden layers       : 25
  Hidden size         : 896
  Output size est.    : 4.53 GiB
  Pooling             : mean
  Max length          : 512
  FROZEN batch        : 32
  Device              : cpu
  Runtime diagnostics : /Volumes/Amirali/hidden_states/experiments/baseline_v5_001/models/Qwen/Qwen2.5-0.5B/datasets/goEmo/metadata/runtime_state.json
✓ DATASET ALREADY COMPLETE (metadata updated): goEmo
  Text-column resolver: exact candidate 'clean_text'

────────────────────────────────────────────────────────────────────────────────────────
DATASET ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Text column         : clean_text
  Samples             : 7,666
  Dataset fingerprint : c96aebef9c5742e9b896
  Hidden layers       : 25
  Hidden size         : 896
  Output size est.    : 0.64 GiB
  Pooling             : mean
  Max length          : 512
  FROZEN batch        : 32
  Device              : cpu
  Runtime diagnostics : /Volumes/Amirali/hidden_states/experiments/baseline_v5_001/models/Qwen/Qwen2.5-0.5B/datasets/ISEAR/metadata/runtime_state.json
  Existing progress   : 3,616/7,666 (47.17%)

ISEAR:  47%|####7     | 3616/7666 [00:00<?, ?sample/s]

[start] starting at absolute sample 3616
[batch] 3616:3648 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 3,648/7,666 (47.59%)
  Newly computed       : 32
  Wall time            : 26.46s
  Throughput           : 1.21 samples/s
  ETA                  : 55m 22.6s
  Current stage        : measurement

  LAST BATCH
    Range              : 3616:3648
    New samples        : 32
    Total              : 26.30s
    Forward            : 24.63s
    Tokenization       : 0.06s
    Input transfer     : 0.00s
    Pooling            : 0.19s
    Conversion         : 0.00s
    Memmap write       : 0.34s
    Flush              : 0.08s
    Sequence length    : 55
    Tokens             : 889
    Token throughput   : 33.81 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 26.297s
    Median batch       : 26.297s
    P95 batch          : 26.297s
    Max batch          : 26.297s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 1.73 GiB
    Process RSS        : 0.8804817199707031
    Peak RSS           : 0.88 GiB
    Minimum RAM        : 1.73 GiB
    External free      : 1744.64 GiB
    Successful batches : 1
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 3648:3680 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 3,680/7,666 (48.00%)
  Newly computed       : 64
  Wall time            : 1m 08.0s
  Throughput           : 0.94 samples/s
  ETA                  : 1h 10m 33.3s
  Current stage        : measurement

  LAST BATCH
    Range              : 3648:3680
    New samples        : 32
    Total              : 41.43s
    Forward            : 38.41s
    Tokenization       : 0.12s
    Input transfer     : 0.00s
    Pooling            : 0.60s
    Conversion         : 0.00s
    Memmap write       : 0.37s
    Flush              : 0.07s
    Sequence length    : 54
    Tokens             : 956
    Token throughput   : 23.08 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 33.861s
    Median batch       : 33.861s
    P95 batch          : 41.426s
    Max batch          : 41.426s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.18 GiB
    Process RSS        : 0.9920845031738281
    Peak RSS           : 0.99 GiB
    Minimum RAM        : 1.73 GiB
    External free      : 1744.63 GiB
    Successful batches : 2
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 3680:3712 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 3,712/7,666 (48.42%)
  Newly computed       : 96
  Wall time            : 1m 38.6s
  Throughput           : 0.97 samples/s
  ETA                  : 1h 7m 41.2s
  Current stage        : measurement

  LAST BATCH
    Range              : 3680:3712
    New samples        : 32
    Total              : 30.59s
    Forward            : 28.19s
    Tokenization       : 0.10s
    Input transfer     : 0.00s
    Pooling            : 0.57s
    Conversion         : 0.00s
    Memmap write       : 0.08s
    Flush              : 0.09s
    Sequence length    : 41
    Tokens             : 734
    Token throughput   : 23.99 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 32.771s
    Median batch       : 30.590s
    P95 batch          : 41.426s
    Max batch          : 41.426s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.53 GiB
    Process RSS        : 1.5329818725585938
    Peak RSS           : 1.53 GiB
    Minimum RAM        : 1.73 GiB
    External free      : 1744.63 GiB
    Successful batches : 3
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 3712:3744 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 3,744/7,666 (48.84%)
  Newly computed       : 128
  Wall time            : 2m 07.2s
  Throughput           : 1.01 samples/s
  ETA                  : 1h 4m 57.0s
  Current stage        : measurement

  LAST BATCH
    Range              : 3712:3744
    New samples        : 32
    Total              : 28.51s
    Forward            : 26.86s
    Tokenization       : 0.06s
    Input transfer     : 0.00s
    Pooling            : 0.31s
    Conversion         : 0.00s
    Memmap write       : 0.04s
    Flush              : 0.09s
    Sequence length    : 34
    Tokens             : 576
    Token throughput   : 20.21 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 31.705s
    Median batch       : 29.548s
    P95 batch          : 41.426s
    Max batch          : 41.426s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.07 GiB
    Process RSS        : 0.7268180847167969
    Peak RSS           : 1.53 GiB
    Minimum RAM        : 1.73 GiB
    External free      : 1744.63 GiB
    Successful batches : 4
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 3744:3776 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 3,776/7,666 (49.26%)
  Newly computed       : 160
  Wall time            : 2m 42.1s
  Throughput           : 0.99 samples/s
  ETA                  : 1h 5m 42.1s
  Current stage        : measurement

  LAST BATCH
    Range              : 3744:3776
    New samples        : 32
    Total              : 34.92s
    Forward            : 32.77s
    Tokenization       : 0.11s
    Input transfer     : 0.00s
    Pooling            : 0.32s
    Conversion         : 0.00s
    Memmap write       : 0.10s
    Flush              : 0.10s
    Sequence length    : 48
    Tokens             : 860
    Token throughput   : 24.63 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 32.347s
    Median batch       : 30.590s
    P95 batch          : 41.426s
    Max batch          : 41.426s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.33 GiB
    Process RSS        : 1.5558929443359375
    Peak RSS           : 1.56 GiB
    Minimum RAM        : 1.73 GiB
    External free      : 1744.63 GiB
    Successful batches : 5
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 3776:3808 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 3,808/7,666 (49.67%)
  Newly computed       : 192
  Wall time            : 3m 24.1s
  Throughput           : 0.94 samples/s
  ETA                  : 1h 8m 20.4s
  Current stage        : measurement

  LAST BATCH
    Range              : 3776:3808
    New samples        : 32
    Total              : 41.87s
    Forward            : 40.55s
    Tokenization       : 0.06s
    Input transfer     : 0.00s
    Pooling            : 0.12s
    Conversion         : 0.00s
    Memmap write       : 0.35s
    Flush              : 0.10s
    Sequence length    : 60
    Tokens             : 773
    Token throughput   : 18.46 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 33.933s
    Median batch       : 32.753s
    P95 batch          : 41.866s
    Max batch          : 41.866s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 1.66 GiB
    Process RSS        : 0.5138320922851562
    Peak RSS           : 1.56 GiB
    Minimum RAM        : 1.66 GiB
    External free      : 1744.63 GiB
    Successful batches : 6
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 3808:3840 processed
[batch] 3840:3872 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 3,872/7,666 (50.51%)
  Newly computed       : 256
  Wall time            : 3m 41.1s
  Throughput           : 1.16 samples/s
  ETA                  : 54m 36.4s
  Current stage        : measurement

  LAST BATCH
    Range              : 3840:3872
    New samples        : 32
    Total              : 6.25s
    Forward            : 5.91s
    Tokenization       : 0.05s
    Input transfer     : 0.00s
    Pooling            : 0.04s
    Conversion         : 0.00s
    Memmap write       : 0.08s
    Flush              : 0.04s
    Sequence length    : 33
    Tokens             : 640
    Token throughput   : 102.40 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 27.571s
    Median batch       : 29.548s
    P95 batch          : 41.866s
    Max batch          : 41.866s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.29 GiB
    Process RSS        : 1.5307388305664062
    Peak RSS           : 1.56 GiB
    Minimum RAM        : 1.66 GiB
    External free      : 1744.63 GiB
    Successful batches : 8
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 3872:3904 processed
[batch] 3904:3936 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 3,936/7,666 (51.34%)
  Newly computed       : 320
  Wall time            : 4m 01.2s
  Throughput           : 1.33 samples/s
  ETA                  : 46m 51.1s
  Current stage        : measurement

  LAST BATCH
    Range              : 3904:3936
    New samples        : 32
    Total              : 12.10s
    Forward            : 11.69s
    Tokenization       : 0.03s
    Input transfer     : 0.00s
    Pooling            : 0.02s
    Conversion         : 0.00s
    Memmap write       : 0.09s
    Flush              : 0.09s
    Sequence length    : 36
    Tokens             : 682
    Token throughput   : 56.36 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 24.054s
    Median batch       : 27.401s
    P95 batch          : 41.866s
    Max batch          : 41.866s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.11 GiB
    Process RSS        : 1.3185691833496094
    Peak RSS           : 1.56 GiB
    Minimum RAM        : 1.66 GiB
    External free      : 1744.63 GiB
    Successful batches : 10
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 3936:3968 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 3,968/7,666 (51.76%)
  Newly computed       : 352
  Wall time            : 4m 17.0s
  Throughput           : 1.37 samples/s
  ETA                  : 44m 59.5s
  Current stage        : measurement

  LAST BATCH
    Range              : 3936:3968
    New samples        : 32
    Total              : 15.67s
    Forward            : 14.77s
    Tokenization       : 0.10s
    Input transfer     : 0.00s
    Pooling            : 0.07s
    Conversion         : 0.00s
    Memmap write       : 0.35s
    Flush              : 0.09s
    Sequence length    : 45
    Tokens             : 832
    Token throughput   : 53.08 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 23.292s
    Median batch       : 26.297s
    P95 batch          : 41.866s
    Max batch          : 41.866s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.42 GiB
    Process RSS        : 1.5705337524414062
    Peak RSS           : 1.57 GiB
    Minimum RAM        : 1.66 GiB
    External free      : 1744.63 GiB
    Successful batches : 11
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 3968:4000 processed
[batch] 4000:4032 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 4,032/7,666 (52.60%)
  Newly computed       : 416
  Wall time            : 4m 45.3s
  Throughput           : 1.46 samples/s
  ETA                  : 41m 32.7s
  Current stage        : measurement

  LAST BATCH
    Range              : 4000:4032
    New samples        : 32
    Total              : 19.04s
    Forward            : 18.27s
    Tokenization       : 0.04s
    Input transfer     : 0.00s
    Pooling            : 0.07s
    Conversion         : 0.00s
    Memmap write       : 0.04s
    Flush              : 0.12s
    Sequence length    : 42
    Tokens             : 807
    Token throughput   : 42.38 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 21.887s
    Median batch       : 19.040s
    P95 batch          : 41.866s
    Max batch          : 41.866s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.26 GiB
    Process RSS        : 1.4897308349609375
    Peak RSS           : 1.57 GiB
    Minimum RAM        : 1.66 GiB
    External free      : 1744.63 GiB
    Successful batches : 13
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 4032:4064 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 4,064/7,666 (53.01%)
  Newly computed       : 448
  Wall time            : 5m 09.0s
  Throughput           : 1.45 samples/s
  ETA                  : 41m 24.7s
  Current stage        : measurement

  LAST BATCH
    Range              : 4032:4064
    New samples        : 32
    Total              : 23.59s
    Forward            : 22.53s
    Tokenization       : 0.13s
    Input transfer     : 0.00s
    Pooling            : 0.16s
    Conversion         : 0.00s
    Memmap write       : 0.09s
    Flush              : 0.09s
    Sequence length    : 54
    Tokens             : 895
    Token throughput   : 37.93 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 22.009s
    Median batch       : 21.317s
    P95 batch          : 41.866s
    Max batch          : 41.866s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.26 GiB
    Process RSS        : 1.386474609375
    Peak RSS           : 1.57 GiB
    Minimum RAM        : 1.66 GiB
    External free      : 1744.63 GiB
    Successful batches : 14
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 4064:4096 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 4,096/7,666 (53.43%)
  Newly computed       : 480
  Wall time            : 5m 42.9s
  Throughput           : 1.40 samples/s
  ETA                  : 42m 30.3s
  Current stage        : measurement

  LAST BATCH
    Range              : 4064:4096
    New samples        : 32
    Total              : 33.77s
    Forward            : 32.50s
    Tokenization       : 0.38s
    Input transfer     : 0.00s
    Pooling            : 0.11s
    Conversion         : 0.00s
    Memmap write       : 0.14s
    Flush              : 0.11s
    Sequence length    : 81
    Tokens             : 817
    Token throughput   : 24.19 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 22.793s
    Median batch       : 23.595s
    P95 batch          : 41.866s
    Max batch          : 41.866s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.46 GiB
    Process RSS        : 1.5447502136230469
    Peak RSS           : 1.57 GiB
    Minimum RAM        : 1.66 GiB
    External free      : 1744.61 GiB
    Successful batches : 15
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 4096:4128 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 4,128/7,666 (53.85%)
  Newly computed       : 512
  Wall time            : 5m 59.6s
  Throughput           : 1.42 samples/s
  ETA                  : 41m 25.1s
  Current stage        : measurement

  LAST BATCH
    Range              : 4096:4128
    New samples        : 32
    Total              : 16.68s
    Forward            : 15.65s
    Tokenization       : 0.10s
    Input transfer     : 0.00s
    Pooling            : 0.09s
    Conversion         : 0.00s
    Memmap write       : 0.08s
    Flush              : 0.09s
    Sequence length    : 44
    Tokens             : 499
    Token throughput   : 29.91 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 22.411s
    Median batch       : 21.317s
    P95 batch          : 41.866s
    Max batch          : 41.866s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.56 GiB
    Process RSS        : 1.5748786926269531
    Peak RSS           : 1.57 GiB
    Minimum RAM        : 1.66 GiB
    External free      : 1744.61 GiB
    Successful batches : 16
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 4128:4160 processed
[batch] 4160:4192 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: ISEAR
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 4,192/7,666 (54.68%)
  Newly computed       : 576
  Wall time            : 6m 20.7s
  Throughput           : 1.51 samples/s
  ETA                  : 38m 16.3s
  Current stage        : measurement

  LAST BATCH
    Range              : 4160:4192
    New samples        : 32
    Total              : 9.37s

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

  ✓ Snapshot ready
    Attempt time        : 5m 49.0s
    Total preparation   : 5m 49.0s
    Checkpoint size     : 2.875 GiB
    Snapshot            : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--Qwen--Qwen2.5-1.5B/snapshots/8faed761d45a263340a0528343f099c05c9a4323

────────────────────────────────────────────────────────────────────────────────────────
MODEL PREFLIGHT
────────────────────────────────────────────────────────────────────────────────────────
  model                             : Qwen/Qwen2.5-1.5B
  model_type                        : qwen2
  architecture                      : decoder
  dtype                             : torch.float32
  device                            : cpu
  layers                            : 28
  hidden_size                       : 1536
  hidden_states                     : 29
  max_length                        : 512
  checkpoint                        : {'active_bytes': 3087471240, 'active_gb': 2.875431664288044, 'inventory': {'safetensors': [{'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--Qwen--Qwen2.5-1.5B/snapshots/8faed761d45a263340a0528343f099c05c9a4323/._model.safetensors', 'filename': '._model.safetensors', 'size_bytes': 4096, 'size_gb': 3.814697265625e-06}, {'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--Qwen--Qwen2.5-1.5B/snapshots/8faed761d45a263340a0528343f099c05c9a4323/model.safetensors', 'filename': 'model.safetensors', 'size_bytes': 3087467144, 'size_gb': 2.8754278495907784}], 'pytorch_bin': [], 'index_files': [], 'safetensors_total_bytes': 3087471240, 'pytorch_bin_total_bytes': 0}}
  estimated_loaded_weight_gb        : 5.750863328576088
  estimated_model_load_peak_gb      : 6.9010359942913055
  memory                            : {'total_gb': 8.0, 'available_gb': 1.8127174377441406, 'used_gb': 3.8536758422851562, 'reserve_gb': 0.5, 'safe_total_memory_gb': 6.4}
  status                            : ok
  ✓ Tokenizer loaded in 0.89s Mode=fast
  TOKENIZER DIAGNOSTICS
    class              : Qwen2TokenizerFast
    vocab size         : 151665
    pad token          : '<|endoftext|>'
    pad source         : checkpoint-defined
    attempts           : [{"mode": "auto_fast", "success": true, "error_type": null, "error": null}]

MODEL LOAD ATTEMPT
  Attempt              : 1/2
  Path                 : primary
  Model                : Qwen/Qwen2.5-1.5B
  Snapshot             : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--Qwen--Qwen2.5-1.5B/snapshots/8faed761d45a263340a0528343f099c05c9a4323
  dtype                : torch.float32
  device               : cpu
  SDPA                 : True
  low_cpu_mem_usage    : True
  LOADING RESULT
    Missing keys        : 0
    Non-core missing    : 0
    Core missing        : 0
    Unexpected keys     : 0
    Mismatched keys     : 0
    Meta tensors        : 0
    Core meta           : 0
    Fatal discrepancy   : False
  FULL LOADING DIAGNOSTICS
{
  "missing_keys": [],
  "unexpected_keys": [],
  "mismatched_keys": [],
  "non_core_missing_keys": [],
  "core_missing_keys": [],
  "all_meta_tensors": [],
  "non_core_meta_tensors": [],
  "core_meta_tensors": [],
  "has_meta_tensors": false,
  "fatal": false
}

✓ MODEL READY
  Load/probe time       : 135.43s
  Backend               : sdpa
  Model device          : cpu
  Hidden states         : 29
  Hidden size           : 1536
  Text-column resolver: exact candidate 'clean_text'

────────────────────────────────────────────────────────────────────────────────────────
DATASET goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Text column         : clean_text
  Samples             : 54,263
  Dataset fingerprint : 6302b3ba58f9886999c7
  Hidden layers       : 29
  Hidden size         : 1536
  Output size est.    : 9.00 GiB
  Pooling             : mean
  Max length          : 512
  FROZEN batch        : 8
  Device              : cpu
  Runtime diagnostics : /Volumes/Amirali/hidden_states/experiments/baseline_v5_001/models/Qwen/Qwen2.5-1.5B/datasets/goEmo/metadata/runtime_state.json
  Existing progress   : 0/54,263 (0.00%)

goEmo:   0%|          | 0/54263 [00:00<?, ?sample/s]

[start] starting at absolute sample 0
[batch] 0:8 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 8/54,263 (0.01%)
  Newly computed       : 8
  Wall time            : 38.73s
  Throughput           : 0.21 samples/s
  ETA                  : 72h 56m 50.4s
  Current stage        : measurement

  LAST BATCH
    Range              : 0:8
    New samples        : 8
    Total              : 38.32s
    Forward            : 37.38s
    Tokenization       : 0.11s
    Input transfer     : 0.00s
    Pooling            : 0.09s
    Conversion         : 0.01s
    Memmap write       : 0.14s
    Flush              : 0.08s
    Sequence length    : 37
    Tokens             : 136
    Token throughput   : 3.55 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 38.316s
    Median batch       : 38.316s
    P95 batch          : 38.316s
    Max batch          : 38.316s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 0.69 GiB
    Process RSS        : 0.46955108642578125
    Peak RSS           : 0.47 GiB
    Minimum RAM        : 0.69 GiB
    External free      : 1731.82 GiB
    Successful batches : 1
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 8:16 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 16/54,263 (0.03%)
  Newly computed       : 16
  Wall time            : 1m 42.5s
  Throughput           : 0.16 samples/s
  ETA                  : 96h 32m 48.8s
  Current stage        : measurement

  LAST BATCH
    Range              : 8:16
    New samples        : 8
    Total              : 1m 03.7s
    Forward            : 1m 02.4s
    Tokenization       : 0.65s
    Input transfer     : 0.00s
    Pooling            : 0.02s
    Conversion         : 0.00s
    Memmap write       : 0.06s
    Flush              : 0.15s
    Sequence length    : 28
    Tokens             : 136
    Token throughput   : 2.14 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 50.992s
    Median batch       : 50.992s
    P95 batch          : 63.667s
    Max batch          : 63.667s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 0.95 GiB
    Process RSS        : 0.920074462890625
    Peak RSS           : 0.92 GiB
    Minimum RAM        : 0.69 GiB
    External free      : 1731.79 GiB
    Successful batches : 2
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 16:24 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 24/54,263 (0.04%)
  Newly computed       : 24
  Wall time            : 3m 35.0s
  Throughput           : 0.11 samples/s
  ETA                  : 134h 59m 57.6s
  Current stage        : measurement

  LAST BATCH
    Range              : 16:24
    New samples        : 8
    Total              : 1m 52.3s
    Forward            : 1m 50.8s
    Tokenization       : 0.58s
    Input transfer     : 0.00s
    Pooling            : 0.08s
    Conversion         : 0.00s
    Memmap write       : 0.12s
    Flush              : 0.12s
    Sequence length    : 18
    Tokens             : 72
    Token throughput   : 0.64 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 71.443s
    Median batch       : 63.667s
    P95 batch          : 112.347s
    Max batch          : 112.347s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 0.85 GiB
    Process RSS        : 0.42020416259765625
    Peak RSS           : 0.92 GiB
    Minimum RAM        : 0.69 GiB
    External free      : 1731.76 GiB
    Successful batches : 3
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 24:32 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 32/54,263 (0.06%)
  Newly computed       : 32
  Wall time            : 5m 47.8s
  Throughput           : 0.09 samples/s
  ETA                  : 163h 43m 29.7s
  Current stage        : measurement

  LAST BATCH
    Range              : 24:32
    New samples        : 8
    Total              : 2m 12.5s
    Forward            : 2m 10.0s
    Tokenization       : 0.81s
    Input transfer     : 0.00s
    Pooling            : 0.09s
    Conversion         : 0.01s
    Memmap write       : 0.04s
    Flush              : 0.18s
    Sequence length    : 27
    Tokens             : 97
    Token throughput   : 0.73 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 86.712s
    Median batch       : 88.007s
    P95 batch          : 132.520s
    Max batch          : 132.520s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 0.83 GiB
    Process RSS        : 0.4992179870605469
    Peak RSS           : 0.92 GiB
    Minimum RAM        : 0.69 GiB
    External free      : 1731.72 GiB
    Successful batches : 4
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 32:40 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 40/54,263 (0.07%)
  Newly computed       : 40
  Wall time            : 7m 16.2s
  Throughput           : 0.09 samples/s
  ETA                  : 164h 13m 58.4s
  Current stage        : measurement

  LAST BATCH
    Range              : 32:40
    New samples        : 8
    Total              : 1m 28.1s
    Forward            : 1m 26.3s
    Tokenization       : 0.96s
    Input transfer     : 0.00s
    Pooling            : 0.07s
    Conversion         : 0.00s
    Memmap write       : 0.09s
    Flush              : 0.17s
    Sequence length    : 24
    Tokens             : 103
    Token throughput   : 1.17 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 86.997s
    Median batch       : 88.135s
    P95 batch          : 132.520s
    Max batch          : 132.520s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 0.91 GiB
    Process RSS        : 0.6471366882324219
    Peak RSS           : 0.92 GiB
    Minimum RAM        : 0.69 GiB
    External free      : 1731.70 GiB
    Successful batches : 5
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 40:48 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 48/54,263 (0.09%)
  Newly computed       : 48
  Wall time            : 9m 18.4s
  Throughput           : 0.09 samples/s
  ETA                  : 175h 11m 36.5s
  Current stage        : measurement

  LAST BATCH
    Range              : 40:48
    New samples        : 8
    Total              : 2m 02.0s
    Forward            : 2m 00.2s
    Tokenization       : 1.08s
    Input transfer     : 0.01s
    Pooling            : 0.06s
    Conversion         : 0.00s
    Memmap write       : 0.09s
    Flush              : 0.15s
    Sequence length    : 30
    Tokens             : 130
    Token throughput   : 1.07 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 92.832s
    Median batch       : 100.241s
    P95 batch          : 132.520s
    Max batch          : 132.520s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 1.08 GiB
    Process RSS        : 0.8758010864257812
    Peak RSS           : 0.92 GiB
    Minimum RAM        : 0.69 GiB
    External free      : 1731.66 GiB
    Successful batches : 6
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 48:56 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 56/54,263 (0.10%)
  Newly computed       : 56
  Wall time            : 13m 42.5s
  Throughput           : 0.07 samples/s
  ETA                  : 221h 10m 02.4s
  Current stage        : measurement

  LAST BATCH
    Range              : 48:56
    New samples        : 8
    Total              : 4m 23.8s
    Forward            : 4m 21.9s
    Tokenization       : 0.29s
    Input transfer     : 0.00s
    Pooling            : 0.09s
    Conversion         : 0.00s
    Memmap write       : 0.05s
    Flush              : 0.19s
    Sequence length    : 23
    Tokens             : 82
    Token throughput   : 0.31 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 117.250s
    Median batch       : 112.347s
    P95 batch          : 263.759s
    Max batch          : 263.759s
    Slow batches       : 1
    Current anomaly    : YES (x2.35)

  MEMORY / STORAGE
    RAM available      : 0.59 GiB
    Process RSS        : 0.10602569580078125
    Peak RSS           : 0.92 GiB
    Minimum RAM        : 0.59 GiB
    External free      : 1731.57 GiB
    Successful batches : 7
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 56:64 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 64/54,263 (0.12%)
  Newly computed       : 64
  Wall time            : 15m 35.1s
  Throughput           : 0.07 samples/s
  ETA                  : 219h 58m 43.2s
  Current stage        : measurement

  LAST BATCH
    Range              : 56:64
    New samples        : 8
    Total              : 1m 52.3s
    Forward            : 1m 49.6s
    Tokenization       : 1.55s
    Input transfer     : 0.00s
    Pooling            : 0.08s
    Conversion         : 0.00s
    Memmap write       : 0.09s
    Flush              : 0.19s
    Sequence length    : 19
    Tokens             : 87
    Token throughput   : 0.77 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 116.631s
    Median batch       : 112.322s
    P95 batch          : 263.759s
    Max batch          : 263.759s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 0.72 GiB
    Process RSS        : 0.104095458984375
    Peak RSS           : 0.92 GiB
    Minimum RAM        : 0.59 GiB
    External free      : 1731.54 GiB
    Successful batches : 8
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 64:72 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 72/54,263 (0.13%)
  Newly computed       : 72
  Wall time            : 17m 37.0s
  Throughput           : 0.07 samples/s
  ETA                  : 220h 58m 53.5s
  Current stage        : measurement

  LAST BATCH
    Range              : 64:72
    New samples        : 8
    Total              : 2m 01.6s
    Forward            : 1m 59.8s
    Tokenization       : 0.89s
    Input transfer     : 0.00s
    Pooling            : 0.10s
    Conversion         : 0.01s
    Memmap write       : 0.05s
    Flush              : 0.11s
    Sequence length    : 17
    Tokens             : 76
    Token throughput   : 0.63 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 117.179s
    Median batch       : 112.347s
    P95 batch          : 263.759s
    Max batch          : 263.759s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 0.88 GiB
    Process RSS        : 0.68450927734375
    Peak RSS           : 0.92 GiB
    Minimum RAM        : 0.59 GiB
    External free      : 1731.50 GiB
    Successful batches : 9
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 72:80 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 80/54,263 (0.15%)
  Newly computed       : 80
  Wall time            : 19m 40.9s
  Throughput           : 0.07 samples/s
  ETA                  : 222h 10m 21.3s
  Current stage        : measurement

  LAST BATCH
    Range              : 72:80
    New samples        : 8
    Total              : 2m 03.7s
    Forward            : 2m 01.5s
    Tokenization       : 1.07s
    Input transfer     : 0.00s
    Pooling            : 0.09s
    Conversion         : 0.00s
    Memmap write       : 0.04s
    Flush              : 0.15s
    Sequence length    : 20
    Tokens             : 88
    Token throughput   : 0.71 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 117.833s
    Median batch       : 116.957s
    P95 batch          : 263.759s
    Max batch          : 263.759s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 0.66 GiB
    Process RSS        : 0.266998291015625
    Peak RSS           : 0.92 GiB
    Minimum RAM        : 0.59 GiB
    External free      : 1733.86 GiB
    Successful batches : 10
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 80:88 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 88/54,263 (0.16%)
  Newly computed       : 88
  Wall time            : 21m 31.5s
  Throughput           : 0.07 samples/s
  ETA                  : 220h 51m 17.7s
  Current stage        : measurement

  LAST BATCH
    Range              : 80:88
    New samples        : 8
    Total              : 1m 50.3s
    Forward            : 1m 48.4s
    Tokenization       : 0.99s
    Input transfer     : 0.00s
    Pooling            : 0.07s
    Conversion         : 0.01s
    Memmap write       : 0.09s
    Flush              : 0.18s
    Sequence length    : 18
    Tokens             : 105
    Token throughput   : 0.95 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 117.150s
    Median batch       : 112.347s
    P95 batch          : 263.759s
    Max batch          : 263.759s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 0.67 GiB
    Process RSS        : 0.3756256103515625
    Peak RSS           : 0.92 GiB
    Minimum RAM        : 0.59 GiB
    External free      : 1734.07 GiB
    Successful batches : 11
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 88:96 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 96/54,263 (0.18%)
  Newly computed       : 96
  Wall time            : 25m 09.9s
  Throughput           : 0.06 samples/s
  ETA                  : 236h 38m 53.3s
  Current stage        : measurement

  LAST BATCH
    Range              : 88:96
    New samples        : 8
    Total              : 3m 38.1s
    Forward            : 3m 33.7s
    Tokenization       : 1.55s
    Input transfer     : 0.00s
    Pooling            : 0.33s
    Conversion         : 0.01s
    Memmap write       : 0.10s
    Flush              : 0.16s
    Sequence length    : 31
    Tokens             : 137
    Token throughput   : 0.63 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 125.566s
    Median batch       : 116.957s
    P95 batch          : 263.759s
    Max batch          : 263.759s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 0.59 GiB
    Process RSS        : 0.17541122436523438
    Peak RSS           : 0.92 GiB
    Minimum RAM        : 0.59 GiB
    External free      : 1734.01 GiB
    Successful batches : 12
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry

In [ ]:
# =============================================================================
# CELL 4 – COLLECT ALL RESULTS FROM DISK (PARTIAL INCLUDED)
# =============================================================================

exp_root = Path("/Volumes/Amirali/hidden_states/experiments/baseline_v5_001")
df_results = load_experiment_results(exp_root)

if not df_results.empty:
    display_title("Extraction Progress")
    display(df_results[['model', 'dataset', 'status', 'completed_samples', 'total_samples']].head(15))
    display_info(f"Total dataset‑model pairs found: <b>{len(df_results)}</b>")
else:
    display_info("No extraction metadata found yet. Run the extraction first (Cell 3).")

In [ ]:
# =============================================================================
# CELL 4.5 – FULL EXPERIMENT AUDIT & VALIDATION
# =============================================================================

from IPython.display import display, HTML
import pandas as pd
import numpy as np

# Path to your experiment
exp_root = Path("/Volumes/Amirali/hidden_states/experiments/baseline_v5_001")

display_title("🔍 Automated Audit & Validation")
display_info("Scanning all model‑dataset pairs and verifying data integrity...")

# Run the audit – this will automatically discover all pairs, validate checksums and sample IDs,
# and optionally fix issues. Set fix_issues=False if you only want a report.
audit_results = Extraction6.audit_experiment(
    experiment_root=exp_root,
    datasets=DATASETS,          # provides the original datasets for sample ID validation
    show_details=False,         # set True if you want per‑dataset detailed prints
    fix_issues=True,            # automatically correct checksum and sample ID mismatches
)

# Convert audit results to a DataFrame for easy viewing
df_audit = pd.DataFrame(audit_results)

# Keep only relevant columns for display
display_cols = [
    "model_name", "dataset_name", "n_samples", "completed_count", "status",
    "checksum_match", "sample_ids_match"
]
if not df_audit.empty:
    df_display = df_audit[display_cols].copy()

    # Clean up status strings and add icons
    status_icons = {
        "complete": "✅",
        "partial": "⏳",
        "missing_files": "❌",
        "missing_metadata": "⚠️",
    }
    df_display["status_icon"] = df_display["status"].map(status_icons).fillna("❓")

    # Boolean columns to checkmarks
    def bool_to_icon(val):
        if val is True:
            return "✅"
        elif val is False:
            return "❌"
        else:
            return "—"

    df_display["checksum"] = df_display["checksum_match"].apply(bool_to_icon)
    df_display["sample_ids"] = df_display["sample_ids_match"].apply(bool_to_icon)

    # Reorder columns for a clean table
    final_cols = ["model_name", "dataset_name", "n_samples", "completed_count", "status_icon", "checksum", "sample_ids"]
    df_final = df_display[final_cols].rename(columns={
        "model_name": "Model",
        "dataset_name": "Dataset",
        "n_samples": "Total Samples",
        "completed_count": "Completed",
        "status_icon": "Status",
        "checksum": "Checksum",
        "sample_ids": "Sample IDs",
    })

    # Create a styled HTML table with custom colors
    def color_status(val):
        if val == "✅":
            return "color: #4caf50;"
        elif val == "⏳":
            return "color: #ff9800;"
        elif val == "❌":
            return "color: #f44336;"
        elif val == "⚠️":
            return "color: #ffeb3b;"
        return ""

    # Display the table
    display(HTML("<h3>Audit Summary – All Model‑Dataset Pairs</h3>"))
    styled_df = df_final.style.applymap(color_status, subset=["Status"])
    display(styled_df)

    # Summary statistics
    total_pairs = len(df_audit)
    complete = (df_audit["status"] == "complete").sum()
    partial = (df_audit["status"] == "partial").sum()
    missing = (df_audit["status"].isin(["missing_files", "missing_metadata"])).sum()
    checksum_ok = df_audit["checksum_match"].sum() if "checksum_match" in df_audit else 0
    ids_ok = df_audit["sample_ids_match"].sum() if "sample_ids_match" in df_audit else 0
    actions_taken = sum(len(r.get("actions_taken", [])) for r in audit_results)

    display_info(f"""
    <b>Total pairs scanned:</b> {total_pairs} &nbsp;|&nbsp;
    <b>✅ Complete:</b> {complete} &nbsp;|&nbsp;
    <b>⏳ Partial:</b> {partial} &nbsp;|&nbsp;
    <b>❌ Missing/Error:</b> {missing} &nbsp;|&nbsp;
    <b>🔧 Checksum OK:</b> {checksum_ok} &nbsp;|&nbsp;
    <b>🔧 Sample IDs OK:</b> {ids_ok} &nbsp;|&nbsp;
    <b>🛠️ Issues fixed:</b> {actions_taken}
    """)

    # Optionally print model-level summary (which models are fully complete)
    model_summary = df_audit.groupby("model_name").apply(
        lambda g: pd.Series({
            "total_datasets": len(g),
            "complete": (g["status"] == "complete").sum(),
            "partial": (g["status"] == "partial").sum(),
            "missing": (g["status"].isin(["missing_files", "missing_metadata"])).sum(),
        })
    ).reset_index()
    model_summary.columns = ["Model", "Datasets", "Complete", "Partial", "Missing/Error"]

    display(HTML("<h3>Per‑Model Completeness</h3>"))
    display(model_summary)

else:
    display_info("No extraction data found to audit.")

In [ ]:
# =============================================================================
# CELL 5 – VISUALISATIONS & ANALYSIS
# =============================================================================

if not df_results.empty:
    # Prepare data for plotting
    df = df_results.copy()
    df['completion_pct'] = df['completed_samples'] / df['total_samples'] * 100
    df['status_clean'] = df['status'].replace({'complete': 'Complete', 'partial': 'Partial', 'failed': 'Failed', 'already_complete': 'Already Complete'})

    sns.set_style("darkgrid")
    plt.rcParams.update({
        'figure.facecolor': '#1e1e1e',
        'axes.facecolor': '#2d2d2d',
        'axes.edgecolor': '#d4d4d4',
        'axes.labelcolor': '#d4d4d4',
        'text.color': '#d4d4d4',
        'xtick.color': '#d4d4d4',
        'ytick.color': '#d4d4d4',
        'grid.color': '#444444',
        'legend.facecolor': '#2d2d2d',
        'legend.edgecolor': '#d4d4d4',
    })

    # ---- 1. Completion status per model/dataset ----
    fig, ax = plt.subplots(figsize=(12, 8))
    pivot = df.pivot_table(index='model', columns='dataset', values='completion_pct', aggfunc='max')
    sns.heatmap(pivot, annot=True, fmt=".0f", cmap="viridis", cbar_kws={'label': 'Completion %'}, ax=ax)
    ax.set_title('Completion Percentage by Model and Dataset', color='#4fc3f7')
    plt.tight_layout()
    plt.show()

    # ---- 2. Throughput (samples/sec) by model ----
    df_complete = df[df['samples_per_second'].notna()]
    if not df_complete.empty:
        fig, ax = plt.subplots(figsize=(14, 6))
        sns.barplot(data=df_complete, x='model', y='samples_per_second', hue='dataset', palette='coolwarm', ax=ax)
        ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
        ax.set_title('Extraction Throughput (samples/sec)', color='#4fc3f7')
        plt.tight_layout()
        plt.show()

    # ---- 3. Total time per model ----
    df_time = df.groupby('model')['elapsed_seconds'].sum().reset_index().sort_values('elapsed_seconds', ascending=False)
    fig, ax = plt.subplots(figsize=(12, 6))
    sns.barplot(data=df_time, x='elapsed_seconds', y='model', palette='magma', ax=ax)
    ax.set_xlabel('Total Elapsed Time (seconds)')
    ax.set_title('Cumulative Extraction Time per Model', color='#4fc3f7')
    plt.tight_layout()
    plt.show()

    # ---- 4. Label coverage for completed datasets ----
    # We'll just display label column info
    display_title("Label Columns Used")
    display(df[['model', 'dataset', 'label_column']].drop_duplicates())
else:
    display_info("No data to visualise. Please run extraction first.")

In [ ]:
# =============================================================================
# CELL 6 – FINAL SUMMARY & EXPORT
# =============================================================================

if not df_results.empty:
    # Save consolidated CSV
    output_csv = exp_root / "extraction_summary.csv"
    df_results.to_csv(output_csv, index=False)
    display_title("Final Report")
    display(df_results)
    display_info(f"Report exported to <code>{output_csv}</code>")
else:
    display_info("Nothing to export yet.")

In [ ]:
discover_extractions(exp_root)

In [ ]:
# Check which models have at least one dataset complete
model_status = df_results.groupby("model")["dataset"].nunique()
print(model_status)

# 🚀 PROJECT REVIEW – EMOTION LEARNING IN LLMs
## `·` State‑of‑‑the‑Art Feedback & Action Plan `·`


# 1. EXECUTIVE SUMMARY

| Aspect | Status | Trend |
|--------|--------|-------|
| Code quality | ⭐⭐⭐⭐⭐ | Exceptional |
| Experimental rigour | ⭐⭐⭐⭐ | Solid controls in place |
| Result interpretation | ⭐⭐ | Needs narrative depth |
| Specification alignment | ⚠️ | QWEN de‑prioritised |
| Literature integration | ⭐⭐⭐ | More explicit links needed |

> ✅ **Overall:** A **diamond in the rough**. Your extraction/probe infrastructure is world‑class, but you’ve over‑invested in the tool and under‑invested in the question. **Refocus on QWEN** and **close the analytical loop** to secure a strong First.


# 2. CRITICAL GAPS & FIXES

## 🔴 1. QWEN is missing from your results
**Spec says:** *“The main focus is QWEN.”*  
**Current reality:** You run 25 small models, QWEN is not the primary focus.

**Fix:**  
- Prioritise extracting **QWEN2‑0.5B** and **QWEN2‑1.5B** (they work on CPU).  
- Acknowledge the limitation honestly in the dissertation.  
- Frame the 25‑model matrix as a **supplementary contribution**, not the core result.

## 🟠 2. Analysis is descriptive, not explanatory
You extract layers and compute F1, but you don’t interpret *why* certain layers excel.

**Fix:**  
- Write a narrative: *“Layer 3 excels because it encodes syntactic patterns correlated with emotional valence.”*  
- Compare to known literature (e.g., Tenney et al. on BERT).  
- Add **ablation studies** (remove emotion words, re‑run probes → see the drop).

## 🟡 3. Performance bottleneck
Extraction runs on CPU, very slow (4–5 hours for small models). QWEN‑7B is impossible.

**Fix:**  
- Acknowledge this as a **constraint** in your write‑up.  
- Frame your codebase as **optimised for minimal resources** – a contribution in itself.  
- If feasible, use **cloud GPU** for a few days to get the critical QWEN data.

## 🟢 4. Logbook: event‑centric, not reflection‑centric
You record *what* you did, but not *what you learned*.

**Fix:**  
- Add “Key learnings” after each work block.  
- Reflect on failed experiments.  
- Document your pivot decisions (e.g., why you switched from JSON to `.npy`).


# 3. ACTION PLAN

## 📌 Phase 1 – Immediate (next 2 weeks)
- [ ] **Run extraction** for:
  - `Qwen/Qwen2-0.5B`
  - `Qwen/Qwen2-1.5B`
  - `Qwen/Qwen2.5-0.5B` (optional)
- [ ] **Run the full probe analysis** on these QWEN states.
- [ ] **Start ablation study**: remove emotion keywords from ISEAR and re‑probe.

## 📌 Phase 2 – Mid‑term (4–6 weeks)
- [ ] **Deepen literature integration** – explicitly link your findings to prior work on BERT and other LLMs.
- [ ] **Add interpretability technique** – e.g., attention visualisation (BertViz) or LIME.
- [ ] **Write the “So what?” narrative** – what are the implications for transfer learning and emotion recognition?

## 📌 Phase 3 – Pre‑submission
- [ ] **Final write‑up structure**: Introduction → Lit Review → Methodology → Results → Discussion → Conclusion.
- [ ] **Unified dashboard**: heatmaps, layer curves, model‑comparison charts, ablation results.
- [ ] **Polish code**: `README.md`, `requirements.txt`, user guide for reproducibility.


# 4. WEEKLY SCHEDULE SUGGESTION (7‑day Power Week)

| Day | Morning (09:00–12:00) | Afternoon (13:00–16:00) | Evening (17:00–19:00) |
|-----|------------------------|--------------------------|------------------------|
| Mon | **Exam Module 1** – Active recall | **Exam Module 2** – Practice questions | **Attendance Module A** – Prep |
| Tue | **Exam Module 3** – Concept mapping | **QWEN extraction** (background) | **Attendance Module B** – Follow‑up |
| Wed | **Exam Module 1** – Past papers | **Data analysis** – Probe results | **Project** – Write‑up |
| Thu | **Exam Module 2** – Flashcards | **Project** – Ablation design | **Rest / Light reading** |
| Fri | **Exam Module 3** – Problem sets | **Project** – Visualisation | **Review week’s progress** |
| Sat | **Consolidation** – All modules (weak areas) | **Project** – Code cleanup | **Social / Recovery** |
| Sun | **Rest / Planning** – No academic work | **Rest / Planning** – No academic work | **Rest / Planning** – No academic work |

> **Start‑day protocol:** 30 min walk → 15 min planning → 1st focus block.  
> **2‑week review:** Ask: *“Am I on track? Is this technique effective? Is my health okay?”*


# 5. FIRST‑CLASS BLUEPRINT (Grade Targets)

| Module Type | Target Grade | Strategy |
|-------------|--------------|----------|
| Exam Module 1 | 72–75% | Past papers, spaced repetition |
| Exam Module 2 | 70–73% | Flashcards, peer teaching |
| Exam Module 3 | 68–72% | Concept maps, problem sets |
| Attendance A | 75–80% | Lead seminars, engage tutor |
| Attendance B | 72–78% | Exceptional coursework, early drafts |

> Current average: 68% → need ~73% across all to secure a strong First.


# 6. KEY RESOURCES & TOOLS

- **Dataset:** GoEmotions + ISEAR (already preprocessed)
- **Models:** QWEN2‑0.5B, 1.5B (primary); BERT (control); 25‑model matrix (supplement)
- **Probe code:** `unified_hidden_state_probe_v4_2.py` (state‑of‑the‑art)
- **Extraction:** `Extraction6_new.py` (resume‑capable, manifest‑tracking)
- **Visualisation:** `Analyser_.py` + `Analyzer_Visualizer_.ipynb`
- **Explainability:** Consider adding **BertViz** or **LIME** for attention maps


# 7. FINAL CHECKLIST

- [ ] QWEN extraction completed
- [ ] QWEN probe analysis done
- [ ] Ablation study executed
- [ ] Attention visualisation added
- [ ] Literature integrated
- [ ] Final write‑up structured
- [ ] Code documented and shareable

> 🏆 **Remember:** The difference between 68% and 78% is **research maturity** – synthesis, self‑critique, and forward thinking. You have the technical skills. Now build the intellectual scaffolding around them.

**You’ve got this.** 🚀