In [1]:

# =============================================================================
# CELL 1 – IMPORTS, DARK THEME, AND HELPERS
# =============================================================================

import importlib
import sys
import json
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display, HTML, Markdown

# -------------------- Dark Theme --------------------
display(HTML("""
<style>
    body, .jp-Notebook, .jp-OutputArea-output, .jp-RenderedHTMLCommon {
        background-color: #1e1e1e !important;
        color: #d4d4d4 !important;
    }
    h2, h3, h4 {
        color: #4fc3f7 !important;
        border-bottom: 2px solid #3498db !important;
        padding-bottom: 4px;
    }
    b, strong { color: #f48fb1 !important; }
    .highlight {
        background-color: #2d2d2d !important;
        padding: 10px;
        border-left: 4px solid #3498db;
        margin: 4px 0;
        color: #d4d4d4;
    }
    code {
        background-color: #333 !important;
        color: #ffcc80 !important;
        padding: 2px 4px;
        border-radius: 4px;
    }
    .dataframe {
        background-color: #2d2d2d !important;
        color: #d4d4d4 !important;
    }
</style>
"""))

# -------------------- Verbosity Flags --------------------
SHOW_VERBOSE = True
SHOW_INFO = True
SHOW_CRITICAL = True
SHOW_DEBUG = True
# For demonstration, we keep them False to reduce output; you can set True as needed.


# -------------------- Import Extraction Module --------------------
import Extraction6_ as Extraction6
importlib.reload(Extraction6)

# -------------------- Helper Functions --------------------
def display_title(title: str):
    display(HTML(f"<h2>{title}</h2>"))

def display_info(message: str):
    display(HTML(f"<div class='highlight'>{message}</div>"))

def load_experiment_results(exp_root: Path) -> pd.DataFrame:
    """
    Load all extraction results from the experiment directory, even if the
    run was interrupted. It reads per-dataset metadata files.
    """
    records = []
    exp_root = Path(exp_root)
    if not exp_root.exists():
        return pd.DataFrame()

    # Search for all extraction.json files under models/*/datasets/*/
    for meta_file in exp_root.rglob("extraction.json"):
        try:
            with open(meta_file, "r") as f:
                meta = json.load(f)
            # Extract relevant fields
            record = {
                "experiment_id": meta.get("experiment_id"),
                "model": meta.get("model", {}).get("name"),
                "dataset": meta.get("dataset", {}).get("name"),
                "status": meta.get("status"),
                "completed_samples": meta.get("performance", {}).get("completed_samples"),
                "total_samples": meta.get("dataset", {}).get("samples"),
                "batch_size": meta.get("extraction", {}).get("batch_size"),
                "pooling": meta.get("extraction", {}).get("pooling"),
                "max_length": meta.get("extraction", {}).get("max_length"),
                "samples_per_second": meta.get("performance", {}).get("samples_per_second"),
                "tokens_per_second": meta.get("performance", {}).get("tokens_per_second"),
                "elapsed_seconds": meta.get("performance", {}).get("elapsed_seconds"),
                "error": None,
                "text_column": meta.get("dataset", {}).get("text_column"),
                "label_column": meta.get("dataset", {}).get("labels", {}).get("label_column"),
            }
            records.append(record)
        except Exception as e:
            # Skip malformed files
            continue
    return pd.DataFrame(records)

print("Environment ready. Dark theme applied.")

Environment ready. Dark theme applied.

In [2]:
# =============================================================================
# CELL 2 – LOAD AND INSPECT DATASETS
# =============================================================================

from Get_Go_Emo import get_go
from Get_Isear import get_isr

goEmo = get_go()
isear = get_isr()

DATASETS = {
    "goEmo": goEmo,
    "ISEAR": isear,
}

for name, df in DATASETS.items():
    display_title(f"Dataset: {name}")
    display_info(f"Shape: {df.shape}")
    display(df.head(2))
    text_col = Extraction6.detect_text_column(df, show_verbose=False)
    label_cols = [c for c in df.columns if c.lower() in ("labels", "label", "emotion", "target")]
    label_col = label_cols[0] if label_cols else None
    display_info(f"Text column: <b>{text_col}</b><br>Label column: <b>{label_col or 'None'}</b><br>Samples: <b>{len(df):,}</b>")

display_title("Unified ID Scheme")
display_info("""
Each sample is assigned a unique integer ID (0..N-1) matching its row index.
This ID links:
• Input text (original DataFrame index)
• Hidden state vector (row in hidden_states.npy)
• Label (row in labels.npy)
No shuffling occurs, guaranteeing one‑to‑one mapping.
""")

  labels                                         clean_text
0   [27]  my favourite food is anything i didnt have to ...
1   [27]  now if he does off himself, everyone will thin...

                                          clean_text  labels
0  during the period of falling in love each time...       1
1          when i was involved in a traffic accident       2

In [3]:
# =============================================================================
# CELL 3 – RUN MODEL MATRIX (ENHANCED, WITH SAFEGUARDS)
# =============================================================================

# This call will automatically resume from existing completions.
# If interrupted, simply re-run this cell to continue.
results = Extraction6.run_model_matrix(
    datasets=DATASETS,
    groups=None,                     # all 25 models
    base_output="/Volumes/Amirali/hidden_states",
    pooling="mean",
    max_length=512,
    use_half_precision=True,
    auto_batch_size=False,
    flush_every_batches=8,
    continue_on_model_error=True,
    show_verbose=SHOW_VERBOSE,
    show_info=SHOW_INFO,
    show_critical=SHOW_CRITICAL,
    show_debug=SHOW_DEBUG,
)

print(f"Returned result records: {len(results)}")

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL MATRIX                                                                         ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Requested experiment : baseline_v5_001
  Transformers         : 4.47.1
  PyTorch              : 2.2.2
  Models               : 25
  Datasets             : 2
  Runtime batch tuning : DISABLED
  Output root          : /Volumes/Amirali/hidden_states
01. [01_encoders] BERT         0.11B  google-bert/bert-base-uncased
02. [01_encoders] DistilBERT   0.066B  distilbert/distilbert-base-uncased
03. [01_encoders] RoBERTa      0.125B  FacebookAI/roberta-base
04. [01_encoders] ELECTRA      0.014B  google/electra-small-discriminator
05. [01_encoders] DeBERTa      0.14B  microsoft/deberta-v3-small
06. [02_early_decoders] GPT          0.124B  gpt2
07. [02_early_decoders] GPT-Neo      0.125B  EleutherAI/gpt-neo-125m
08. [02_early_decoders] OPT          0.125B  facebook/opt-125m
09. [03_tiny_modern] SmolLM2      0.135B  HuggingFaceTB/SmolLM2-135M
10. [03_tiny_modern] SmolLM2      0.36B  HuggingFaceTB/SmolLM2-360M
11. [03_tiny_modern] Gemma        0.27B  google/gemma-3-270m
12. [03_tiny_modern] Qwen         0.5B  Qwen/Qwen2-0.5B
13. [03_tiny_modern] Qwen         0.5B  Qwen/Qwen2.5-0.5B
14. [03_tiny_modern] Qwen         0.6B  Qwen/Qwen3-0.6B-Base
15. [04_qwen_scaling] Qwen         1.5B  Qwen/Qwen2-1.5B
16. [04_qwen_scaling] Qwen         1.54B  Qwen/Qwen2.5-1.5B
17. [04_qwen_scaling] Qwen         3.09B  Qwen/Qwen2.5-3B
18. [04_qwen_scaling] Qwen         1.7B  Qwen/Qwen3-1.7B-Base
19. [05_independent_small] SmolLM2      1.7B  HuggingFaceTB/SmolLM2-1.7B
20. [05_independent_small] TinyLlama    1.1B  TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
21. [05_independent_small] Gemma        1B  google/gemma-3-1b-pt
22. [05_independent_small] Llama        1B  meta-llama/Llama-3.2-1B
23. [06_stretch] Qwen         4B  Qwen/Qwen3-4B-Base
24. [06_stretch] Llama        3B  meta-llama/Llama-3.2-3B
25. [06_stretch] Gemma        4B  google/gemma-3-4b-pt

↻ EXISTING EXPERIMENT DETECTED
  Experiment ID        : baseline_v5_001
  Saved hyperparameter : d90449246241487f
  Manifest             : /Volumes/Amirali/hidden_states/experiments/baseline_v5_001/run_manifest.json
  The saved experiment configuration is authoritative.
  Current-call overrides are ignored for this resume.
  Requested overrides  : {'pooling': 'mean', 'max_length': 512, 'use_half_precision': True, 'flush_every_batches': 8}


╔══════════════════════════════════════════════════════════════════════════════════════╗
║ HIDDEN STATE EXTRACTION EXPERIMENT                                                   ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Experiment ID       : baseline_v5_001
  Hyperparameter hash : d90449246241487f
  Device              : cpu
  Models requested    : 25
  Datasets            : 2
  Pooling             : mean
  Max sequence length : 512
  Runtime batch tuning: DISABLED
  Existing experiment : YES
  Output root         : /Volumes/Amirali/hidden_states/experiments/baseline_v5_001
  Transformers        : 4.47.1
  PyTorch             : 2.2.2

────────────────────────────────────────────────────────────────────────────────────────
SYSTEM / STORAGE REPORT
  Architecture        : x86_64
  Logical CPUs        : 8
  PyTorch threads     : 4
  PyTorch interop     : 8
  Python              : 3.12.0
  RAM total           : 8.00 GiB
  RAM available       : 2.39 GiB
  Adaptive reserve    : 0.50 GiB
  External free       : 1750.41 GiB
  System fingerprint  : d45c07bfe59422f0

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 1/25 :: google-bert/bert-base-uncased                                          ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : BERT
  Generation          : 2018
  Parameters          : 0.11B
  Architecture        : encoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: metadata core fields differ; metadata not updated
  Repaired ISEAR: updated extraction.json with current experiment fields
  Updated metadata for ISEAR
  HF root         : /Volumes/Amirali/hidden_states/huggingface_cache ✓
  Hub cache       : /Volumes/Amirali/hidden_states/huggingface_cache/hub ✓
  Xet cache       : /Volumes/Amirali/hidden_states/huggingface_cache/xet ✓
  Assets cache    : /Volumes/Amirali/hidden_states/huggingface_cache/assets ✓

→ Preparing Hugging Face model: google-bert/bert-base-uncased
  Pinned revision      : 86b5e0934494bd15c9632b12f734a8a67f723594
  Preparation attempt 1/4
  DOWNLOAD DIAGNOSTICS
    Revision             : 86b5e0934494bd15c9632b12f734a8a67f723594
    Cache                : /Volumes/Amirali/hidden_states/huggingface_cache/hub
    Workers              : 4
    ETag timeout         : 20.0s
    Allow patterns       : ['config.json', 'generation_config.json', 'tokenizer_config.json', 'tokenizer.json', 'special_tokens_map.json', 'added_tokens.json', 'vocab.json', 'merges.txt', 'spiece.model', 'spm.model', 'sentencepiece.bpe.model', 'tokenizer.model', 'vocab.txt', 'LICENSE*', 'README.md', '*.json', '*.safetensors']
    Ignore patterns      : ['*.h5', '*.msgpack', '*.ot', 'tf_model.*', 'flax_model.*', 'rust_model.ot', '*.onnx', '*.gguf', '*.ggml', '*.bin']

Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]

  ✓ Snapshot ready
    Attempt time        : 1.14s
    Total preparation   : 1.17s
    Checkpoint size     : 0.410 GiB
    Snapshot            : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--google-bert--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594

────────────────────────────────────────────────────────────────────────────────────────
MODEL PREFLIGHT
────────────────────────────────────────────────────────────────────────────────────────
  model                             : google-bert/bert-base-uncased
  model_type                        : bert
  architecture                      : encoder
  dtype                             : torch.float32
  device                            : cpu
  layers                            : 12
  hidden_size                       : 768
  hidden_states                     : 13
  max_length                        : 512
  checkpoint                        : {'active_bytes': 440453864, 'active_gb': 0.4102046266198158, 'inventory': {'safetensors': [{'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--google-bert--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594/._model.safetensors', 'filename': '._model.safetensors', 'size_bytes': 4096, 'size_gb': 3.814697265625e-06}, {'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--google-bert--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594/model.safetensors', 'filename': 'model.safetensors', 'size_bytes': 440449768, 'size_gb': 0.4102008119225502}], 'pytorch_bin': [{'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--google-bert--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594/._pytorch_model.bin', 'filename': '._pytorch_model.bin', 'size_bytes': 4096, 'size_gb': 3.814697265625e-06}, {'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--google-bert--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594/coreml/fill-mask/float32_model.mlpackage/Data/com.apple.CoreML/weights/._weight.bin', 'filename': '._weight.bin', 'size_bytes': 4096, 'size_gb': 3.814697265625e-06}, {'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--google-bert--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594/coreml/fill-mask/float32_model.mlpackage/Data/com.apple.CoreML/weights/weight.bin', 'filename': 'weight.bin', 'size_bytes': 531833856, 'size_gb': 0.49530887603759766}, {'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--google-bert--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594/pytorch_model.bin', 'filename': 'pytorch_model.bin', 'size_bytes': 440473133, 'size_gb': 0.4102225722745061}], 'index_files': [], 'safetensors_total_bytes': 440453864, 'pytorch_bin_total_bytes': 972315181}}
  estimated_loaded_weight_gb        : 0.4102046266198158
  estimated_model_load_peak_gb      : 0.49224555194377895
  memory                            : {'total_gb': 8.0, 'available_gb': 2.3805885314941406, 'used_gb': 4.408962249755859, 'reserve_gb': 0.5, 'safe_total_memory_gb': 6.4}
  status                            : ok
  ✓ Tokenizer loaded in 0.12s Mode=fast
  TOKENIZER DIAGNOSTICS
    class              : BertTokenizerFast
    vocab size         : 30522
    pad token          : '[PAD]'
    pad source         : checkpoint-defined
    attempts           : [{"mode": "auto_fast", "success": true, "error_type": null, "error": null}]

MODEL LOAD ATTEMPT
  Attempt              : 1/2
  Path                 : primary
  Model                : google-bert/bert-base-uncased
  Snapshot             : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--google-bert--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594
  dtype                : torch.float32
  device               : cpu
  SDPA                 : True
  low_cpu_mem_usage    : True
  LOADING RESULT
    Missing keys        : 0
    Non-core missing    : 0
    Core missing        : 0
    Unexpected keys     : 7
    Mismatched keys     : 0
    Meta tensors        : 0
    Core meta           : 0
    Fatal discrepancy   : False
  FULL LOADING DIAGNOSTICS
{
  "missing_keys": [],
  "unexpected_keys": [
    "cls.predictions.bias",
    "cls.predictions.transform.LayerNorm.bias",
    "cls.predictions.transform.LayerNorm.weight",
    "cls.predictions.transform.dense.bias",
    "cls.predictions.transform.dense.weight",
    "cls.seq_relationship.bias",
    "cls.seq_relationship.weight"
  ],
  "mismatched_keys": [],
  "non_core_missing_keys": [],
  "core_missing_keys": [],
  "all_meta_tensors": [],
  "non_core_meta_tensors": [],
  "core_meta_tensors": [],
  "has_meta_tensors": false,
  "fatal": false
}

✓ MODEL READY
  Load/probe time       : 10.77s
  Backend               : sdpa
  Model device          : cpu
  Hidden states         : 13
  Hidden size           : 768
  Text-column resolver: exact candidate 'clean_text'

────────────────────────────────────────────────────────────────────────────────────────
DATASET goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Text column         : clean_text
  Samples             : 54,263
  Dataset fingerprint : 6302b3ba58f9886999c7
  Hidden layers       : 13
  Hidden size         : 768
  Output size est.    : 2.02 GiB
  Pooling             : mean
  Max length          : 512
  FROZEN batch        : 64
  Device              : cpu
  Runtime diagnostics : /Volumes/Amirali/hidden_states/experiments/baseline_v5_001/models/google-bert/bert-base-uncased/datasets/goEmo/metadata/runtime_state.json

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
MODEL FAILED: google-bert/bert-base-uncased
Error: RuntimeError: COMPLETION MAP IS FULL BUT DATASET PROVENANCE DOES NOT MATCH THE CURRENT EXPERIMENT
Frozen batch: 64
Hyperparameter hash: d90449246241487f
Traceback:
Traceback (most recent call last):
  File "/Users/amirali/Desktop/Year 3/Final Year Project/Final-Year-Project/Extraction6_.py", line 1588, in _run_resolved_experiment
    result = extract_dataset(model, tokenizer, dataset, None, build_dataset_directory(exp_root, model_name, dataset_name), frozen_batch, params.pooling, params.max_length, np.float32 if params.storage_dtype == "float32" else np.float16, device, model_name, dataset_name, snapshot, False, frozen_batch, params.flush_every_batches, params.flush_every_seconds, show_verbose, show_info, show_critical, show_debug, params.experiment_id, params.config_hash)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amirali/Desktop/Year 3/Final Year Project/Final-Year-Project/Extraction6_.py", line 1444, in extract_dataset
    raise RuntimeError("COMPLETION MAP IS FULL BUT DATASET PROVENANCE DOES NOT MATCH THE CURRENT EXPERIMENT")
RuntimeError: COMPLETION MAP IS FULL BUT DATASET PROVENANCE DOES NOT MATCH THE CURRENT EXPERIMENT

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 2/25 :: distilbert/distilbert-base-uncased                                     ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : DistilBERT
  Generation          : 2019
  Parameters          : 0.066B
  Architecture        : encoder
  Training status     : pretrained_distilled
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: updated extraction.json with current experiment fields
  Updated metadata for goEmo
  Repaired ISEAR: updated extraction.json with current experiment fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 3/25 :: FacebookAI/roberta-base                                                ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : RoBERTa
  Generation          : 2019
  Parameters          : 0.125B
  Architecture        : encoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: updated extraction.json with current experiment fields
  Updated metadata for goEmo
  Repaired ISEAR: updated extraction.json with current experiment fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 4/25 :: google/electra-small-discriminator                                     ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : ELECTRA
  Generation          : 2020
  Parameters          : 0.014B
  Architecture        : encoder
  Training status     : pretrained_discriminator
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: updated extraction.json with current experiment fields
  Updated metadata for goEmo
  Repaired ISEAR: updated extraction.json with current experiment fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 5/25 :: microsoft/deberta-v3-small                                             ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : DeBERTa
  Generation          : 2021
  Parameters          : 0.14B
  Architecture        : encoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  HF root         : /Volumes/Amirali/hidden_states/huggingface_cache ✓
  Hub cache       : /Volumes/Amirali/hidden_states/huggingface_cache/hub ✓
  Xet cache       : /Volumes/Amirali/hidden_states/huggingface_cache/xet ✓
  Assets cache    : /Volumes/Amirali/hidden_states/huggingface_cache/assets ✓

→ Preparing Hugging Face model: microsoft/deberta-v3-small
  Pinned revision      : a36c739020e01763fe789b4b85e2df55d6180012
  Preparation attempt 1/4
  DOWNLOAD DIAGNOSTICS
    Revision             : a36c739020e01763fe789b4b85e2df55d6180012
    Cache                : /Volumes/Amirali/hidden_states/huggingface_cache/hub
    Workers              : 4
    ETag timeout         : 20.0s
    Allow patterns       : ['config.json', 'generation_config.json', 'tokenizer_config.json', 'tokenizer.json', 'special_tokens_map.json', 'added_tokens.json', 'vocab.json', 'merges.txt', 'spiece.model', 'spm.model', 'sentencepiece.bpe.model', 'tokenizer.model', 'vocab.txt', 'LICENSE*', 'README.md', '*.json', '*.bin']
    Ignore patterns      : ['*.h5', '*.msgpack', '*.ot', 'tf_model.*', 'flax_model.*', 'rust_model.ot', '*.onnx', '*.gguf', '*.ggml']

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

  ✓ Snapshot ready
    Attempt time        : 0.61s
    Total preparation   : 0.64s
    Checkpoint size     : 0.266 GiB
    Snapshot            : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--microsoft--deberta-v3-small/snapshots/a36c739020e01763fe789b4b85e2df55d6180012

────────────────────────────────────────────────────────────────────────────────────────
MODEL PREFLIGHT
────────────────────────────────────────────────────────────────────────────────────────
  model                             : microsoft/deberta-v3-small
  model_type                        : deberta-v2
  architecture                      : encoder
  dtype                             : torch.float32
  device                            : cpu
  layers                            : 6
  hidden_size                       : 768
  hidden_states                     : 7
  max_length                        : 512
  checkpoint                        : {'active_bytes': 286063365, 'active_gb': 0.26641726959496737, 'inventory': {'safetensors': [], 'pytorch_bin': [{'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--microsoft--deberta-v3-small/snapshots/a36c739020e01763fe789b4b85e2df55d6180012/._pytorch_model.bin', 'filename': '._pytorch_model.bin', 'size_bytes': 4096, 'size_gb': 3.814697265625e-06}, {'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--microsoft--deberta-v3-small/snapshots/a36c739020e01763fe789b4b85e2df55d6180012/pytorch_model.bin', 'filename': 'pytorch_model.bin', 'size_bytes': 286059269, 'size_gb': 0.26641345489770174}], 'index_files': [], 'safetensors_total_bytes': 0, 'pytorch_bin_total_bytes': 286063365}}
  estimated_loaded_weight_gb        : 0.26641726959496737
  estimated_model_load_peak_gb      : 0.31970072351396084
  memory                            : {'total_gb': 8.0, 'available_gb': 2.457294464111328, 'used_gb': 4.563488006591797, 'reserve_gb': 0.5, 'safe_total_memory_gb': 6.4}
  status                            : ok
  Fast tokenizer failed: ValueError: Converting from Tiktoken failed, if a converter for SentencePiece is available, provide a model path with a SentencePiece tokenizer.model file.Currently available slow->fast convertors: ['AlbertTokenizer', 'BartTokenizer', 'BarthezTokenizer', 'BertTokenizer', 'BigBirdTokenizer', 'BlenderbotTokenizer', 'CamembertTokenizer', 'CLIPTokenizer', 'CodeGenTokenizer', 'ConvBertTokenizer', 'DebertaTokenizer', 'DebertaV2Tokenizer', 'DistilBertTokenizer', 'DPRReaderTokenizer', 'DPRQuestionEncoderTokenizer', 'DPRContextEncoderTokenizer', 'ElectraTokenizer', 'FNetTokenizer', 'FunnelTokenizer', 'GPT2Tokenizer', 'HerbertTokenizer', 'LayoutLMTokenizer', 'LayoutLMv2Tokenizer', 'LayoutLMv3Tokenizer', 'LayoutXLMTokenizer', 'LongformerTokenizer', 'LEDTokenizer', 'LxmertTokenizer', 'MarkupLMTokenizer', 'MBartTokenizer', 'MBart50Tokenizer', 'MPNetTokenizer', 'MobileBertTokenizer', 'MvpTokenizer', 'NllbTokenizer', 'OpenAIGPTTokenizer', 'PegasusTokenizer', 'Qwen2Tokenizer', 'RealmTokenizer', 'ReformerTokenizer', 'RemBertTokenizer', 'RetriBertTokenizer', 'RobertaTokenizer', 'RoFormerTokenizer', 'SeamlessM4TTokenizer', 'SqueezeBertTokenizer', 'T5Tokenizer', 'UdopTokenizer', 'WhisperTokenizer', 'XLMRobertaTokenizer', 'XLNetTokenizer', 'SplinterTokenizer', 'XGLMTokenizer', 'LlamaTokenizer', 'CodeLlamaTokenizer', 'GemmaTokenizer', 'Phi3Tokenizer']
  Slow tokenizer failed: ValueError: Converting from Tiktoken failed, if a converter for SentencePiece is available, provide a model path with a SentencePiece tokenizer.model file.Currently available slow->fast convertors: ['AlbertTokenizer', 'BartTokenizer', 'BarthezTokenizer', 'BertTokenizer', 'BigBirdTokenizer', 'BlenderbotTokenizer', 'CamembertTokenizer', 'CLIPTokenizer', 'CodeGenTokenizer', 'ConvBertTokenizer', 'DebertaTokenizer', 'DebertaV2Tokenizer', 'DistilBertTokenizer', 'DPRReaderTokenizer', 'DPRQuestionEncoderTokenizer', 'DPRContextEncoderTokenizer', 'ElectraTokenizer', 'FNetTokenizer', 'FunnelTokenizer', 'GPT2Tokenizer', 'HerbertTokenizer', 'LayoutLMTokenizer', 'LayoutLMv2Tokenizer', 'LayoutLMv3Tokenizer', 'LayoutXLMTokenizer', 'LongformerTokenizer', 'LEDTokenizer', 'LxmertTokenizer', 'MarkupLMTokenizer', 'MBartTokenizer', 'MBart50Tokenizer', 'MPNetTokenizer', 'MobileBertTokenizer', 'MvpTokenizer', 'NllbTokenizer', 'OpenAIGPTTokenizer', 'PegasusTokenizer', 'Qwen2Tokenizer', 'RealmTokenizer', 'ReformerTokenizer', 'RemBertTokenizer', 'RetriBertTokenizer', 'RobertaTokenizer', 'RoFormerTokenizer', 'SeamlessM4TTokenizer', 'SqueezeBertTokenizer', 'T5Tokenizer', 'UdopTokenizer', 'WhisperTokenizer', 'XLMRobertaTokenizer', 'XLNetTokenizer', 'SplinterTokenizer', 'XGLMTokenizer', 'LlamaTokenizer', 'CodeLlamaTokenizer', 'GemmaTokenizer', 'Phi3Tokenizer']

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
MODEL FAILED: microsoft/deberta-v3-small
Error: RuntimeError: TOKENIZER LOAD FAILED
Model: microsoft/deberta-v3-small
Snapshot: /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--microsoft--deberta-v3-small/snapshots/a36c739020e01763fe789b4b85e2df55d6180012
Attempts:
[
  {
    "mode": "auto_fast",
    "success": false,
    "error_type": "ValueError",
    "error": "Converting from Tiktoken failed, if a converter for SentencePiece is available, provide a model path with a SentencePiece tokenizer.model file.Currently available slow->fast convertors: ['AlbertTokenizer', 'BartTokenizer', 'BarthezTokenizer', 'BertTokenizer', 'BigBirdTokenizer', 'BlenderbotTokenizer', 'CamembertTokenizer', 'CLIPTokenizer', 'CodeGenTokenizer', 'ConvBertTokenizer', 'DebertaTokenizer', 'DebertaV2Tokenizer', 'DistilBertTokenizer', 'DPRReaderTokenizer', 'DPRQuestionEncoderTokenizer', 'DPRContextEncoderTokenizer', 'ElectraTokenizer', 'FNetTokenizer', 'FunnelTokenizer', 'GPT2Tokenizer', 'HerbertTokenizer', 'LayoutLMTokenizer', 'LayoutLMv2Tokenizer', 'LayoutLMv3Tokenizer', 'LayoutXLMTokenizer', 'LongformerTokenizer', 'LEDTokenizer', 'LxmertTokenizer', 'MarkupLMTokenizer', 'MBartTokenizer', 'MBart50Tokenizer', 'MPNetTokenizer', 'MobileBertTokenizer', 'MvpTokenizer', 'NllbTokenizer', 'OpenAIGPTTokenizer', 'PegasusTokenizer', 'Qwen2Tokenizer', 'RealmTokenizer', 'ReformerTokenizer', 'RemBertTokenizer', 'RetriBertTokenizer', 'RobertaTokenizer', 'RoFormerTokenizer', 'SeamlessM4TTokenizer', 'SqueezeBertTokenizer', 'T5Tokenizer', 'UdopTokenizer', 'WhisperTokenizer', 'XLMRobertaTokenizer', 'XLNetTokenizer', 'SplinterTokenizer', 'XGLMTokenizer', 'LlamaTokenizer', 'CodeLlamaTokenizer', 'GemmaTokenizer', 'Phi3Tokenizer']"
  },
  {
    "mode": "auto_slow",
    "success": false,
    "error_type": "ValueError",
    "error": "Converting from Tiktoken failed, if a converter for SentencePiece is available, provide a model path with a SentencePiece tokenizer.model file.Currently available slow->fast convertors: ['AlbertTokenizer', 'BartTokenizer', 'BarthezTokenizer', 'BertTokenizer', 'BigBirdTokenizer', 'BlenderbotTokenizer', 'CamembertTokenizer', 'CLIPTokenizer', 'CodeGenTokenizer', 'ConvBertTokenizer', 'DebertaTokenizer', 'DebertaV2Tokenizer', 'DistilBertTokenizer', 'DPRReaderTokenizer', 'DPRQuestionEncoderTokenizer', 'DPRContextEncoderTokenizer', 'ElectraTokenizer', 'FNetTokenizer', 'FunnelTokenizer', 'GPT2Tokenizer', 'HerbertTokenizer', 'LayoutLMTokenizer', 'LayoutLMv2Tokenizer', 'LayoutLMv3Tokenizer', 'LayoutXLMTokenizer', 'LongformerTokenizer', 'LEDTokenizer', 'LxmertTokenizer', 'MarkupLMTokenizer', 'MBartTokenizer', 'MBart50Tokenizer', 'MPNetTokenizer', 'MobileBertTokenizer', 'MvpTokenizer', 'NllbTokenizer', 'OpenAIGPTTokenizer', 'PegasusTokenizer', 'Qwen2Tokenizer', 'RealmTokenizer', 'ReformerTokenizer', 'RemBertTokenizer', 'RetriBertTokenizer', 'RobertaTokenizer', 'RoFormerTokenizer', 'SeamlessM4TTokenizer', 'SqueezeBertTokenizer', 'T5Tokenizer', 'UdopTokenizer', 'WhisperTokenizer', 'XLMRobertaTokenizer', 'XLNetTokenizer', 'SplinterTokenizer', 'XGLMTokenizer', 'LlamaTokenizer', 'CodeLlamaTokenizer', 'GemmaTokenizer', 'Phi3Tokenizer']"
  },
  {
    "mode": "explicit_deberta_sentencepiece",
    "success": false,
    "error_type": "ImportError",
    "error": "\nDebertaV2Tokenizer requires the SentencePiece library but it was not found in your environment. Checkout the instructions on the\ninstallation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones\nthat match your environment. Please note that you may need to restart your runtime after installation.\n"
  }
]
Frozen batch: 64
Hyperparameter hash: d90449246241487f
Traceback:
Traceback (most recent call last):
  File "/Users/amirali/Desktop/Year 3/Final Year Project/Final-Year-Project/Extraction6_.py", line 1585, in _run_resolved_experiment
    tokenizer = load_tokenizer(snapshot, model_name, spec.trust_remote_code, show_verbose, show_info); model, backend, diagnostics, load_time = load_model(snapshot, model_name, tokenizer, dtype, device, spec.trust_remote_code, params.use_sdpa, params.strict_meta_validation, params.max_length, show_verbose, show_info, show_critical)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amirali/Desktop/Year 3/Final Year Project/Final-Year-Project/Extraction6_.py", line 921, in load_tokenizer
    if tokenizer is None: raise RuntimeError("TOKENIZER LOAD FAILED\n" f"Model: {model_name}\n" f"Snapshot: {snapshot}\n" f"Attempts:\n{json.dumps(attempts, indent=2, default=str)}")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: TOKENIZER LOAD FAILED
Model: microsoft/deberta-v3-small
Snapshot: /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--microsoft--deberta-v3-small/snapshots/a36c739020e01763fe789b4b85e2df55d6180012
Attempts:
[
  {
    "mode": "auto_fast",
    "success": false,
    "error_type": "ValueError",
    "error": "Converting from Tiktoken failed, if a converter for SentencePiece is available, provide a model path with a SentencePiece tokenizer.model file.Currently available slow->fast convertors: ['AlbertTokenizer', 'BartTokenizer', 'BarthezTokenizer', 'BertTokenizer', 'BigBirdTokenizer', 'BlenderbotTokenizer', 'CamembertTokenizer', 'CLIPTokenizer', 'CodeGenTokenizer', 'ConvBertTokenizer', 'DebertaTokenizer', 'DebertaV2Tokenizer', 'DistilBertTokenizer', 'DPRReaderTokenizer', 'DPRQuestionEncoderTokenizer', 'DPRContextEncoderTokenizer', 'ElectraTokenizer', 'FNetTokenizer', 'FunnelTokenizer', 'GPT2Tokenizer', 'HerbertTokenizer', 'LayoutLMTokenizer', 'LayoutLMv2Tokenizer', 'LayoutLMv3Tokenizer', 'LayoutXLMTokenizer', 'LongformerTokenizer', 'LEDTokenizer', 'LxmertTokenizer', 'MarkupLMTokenizer', 'MBartTokenizer', 'MBart50Tokenizer', 'MPNetTokenizer', 'MobileBertTokenizer', 'MvpTokenizer', 'NllbTokenizer', 'OpenAIGPTTokenizer', 'PegasusTokenizer', 'Qwen2Tokenizer', 'RealmTokenizer', 'ReformerTokenizer', 'RemBertTokenizer', 'RetriBertTokenizer', 'RobertaTokenizer', 'RoFormerTokenizer', 'SeamlessM4TTokenizer', 'SqueezeBertTokenizer', 'T5Tokenizer', 'UdopTokenizer', 'WhisperTokenizer', 'XLMRobertaTokenizer', 'XLNetTokenizer', 'SplinterTokenizer', 'XGLMTokenizer', 'LlamaTokenizer', 'CodeLlamaTokenizer', 'GemmaTokenizer', 'Phi3Tokenizer']"
  },
  {
    "mode": "auto_slow",
    "success": false,
    "error_type": "ValueError",
    "error": "Converting from Tiktoken failed, if a converter for SentencePiece is available, provide a model path with a SentencePiece tokenizer.model file.Currently available slow->fast convertors: ['AlbertTokenizer', 'BartTokenizer', 'BarthezTokenizer', 'BertTokenizer', 'BigBirdTokenizer', 'BlenderbotTokenizer', 'CamembertTokenizer', 'CLIPTokenizer', 'CodeGenTokenizer', 'ConvBertTokenizer', 'DebertaTokenizer', 'DebertaV2Tokenizer', 'DistilBertTokenizer', 'DPRReaderTokenizer', 'DPRQuestionEncoderTokenizer', 'DPRContextEncoderTokenizer', 'ElectraTokenizer', 'FNetTokenizer', 'FunnelTokenizer', 'GPT2Tokenizer', 'HerbertTokenizer', 'LayoutLMTokenizer', 'LayoutLMv2Tokenizer', 'LayoutLMv3Tokenizer', 'LayoutXLMTokenizer', 'LongformerTokenizer', 'LEDTokenizer', 'LxmertTokenizer', 'MarkupLMTokenizer', 'MBartTokenizer', 'MBart50Tokenizer', 'MPNetTokenizer', 'MobileBertTokenizer', 'MvpTokenizer', 'NllbTokenizer', 'OpenAIGPTTokenizer', 'PegasusTokenizer', 'Qwen2Tokenizer', 'RealmTokenizer', 'ReformerTokenizer', 'RemBertTokenizer', 'RetriBertTokenizer', 'RobertaTokenizer', 'RoFormerTokenizer', 'SeamlessM4TTokenizer', 'SqueezeBertTokenizer', 'T5Tokenizer', 'UdopTokenizer', 'WhisperTokenizer', 'XLMRobertaTokenizer', 'XLNetTokenizer', 'SplinterTokenizer', 'XGLMTokenizer', 'LlamaTokenizer', 'CodeLlamaTokenizer', 'GemmaTokenizer', 'Phi3Tokenizer']"
  },
  {
    "mode": "explicit_deberta_sentencepiece",
    "success": false,
    "error_type": "ImportError",
    "error": "\nDebertaV2Tokenizer requires the SentencePiece library but it was not found in your environment. Checkout the instructions on the\ninstallation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones\nthat match your environment. Please note that you may need to restart your runtime after installation.\n"
  }
]

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 6/25 :: gpt2                                                                   ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : GPT
  Generation          : 2019
  Parameters          : 0.124B
  Architecture        : decoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: updated extraction.json with current experiment fields
  Updated metadata for goEmo
  Repaired ISEAR: updated extraction.json with current experiment fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 7/25 :: EleutherAI/gpt-neo-125m                                                ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : GPT-Neo
  Generation          : 2021
  Parameters          : 0.125B
  Architecture        : decoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: updated extraction.json with current experiment fields
  Updated metadata for goEmo
  Repaired ISEAR: updated extraction.json with current experiment fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 8/25 :: facebook/opt-125m                                                      ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : OPT
  Generation          : 2022
  Parameters          : 0.125B
  Architecture        : decoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  Repaired goEmo: updated extraction.json with current experiment fields
  Updated metadata for goEmo
  Repaired ISEAR: updated extraction.json with current experiment fields
  Updated metadata for ISEAR
✓ SKIPPED — all datasets already complete.

╔══════════════════════════════════════════════════════════════════════════════════════╗
║ MODEL 9/25 :: HuggingFaceTB/SmolLM2-135M                                             ║
╚══════════════════════════════════════════════════════════════════════════════════════╝
  Family              : SmolLM2
  Generation          : 2024
  Parameters          : 0.135B
  Architecture        : decoder
  Training status     : pretrained
  FROZEN batch        : 64
  Gated               : False
  HF root         : /Volumes/Amirali/hidden_states/huggingface_cache ✓
  Hub cache       : /Volumes/Amirali/hidden_states/huggingface_cache/hub ✓
  Xet cache       : /Volumes/Amirali/hidden_states/huggingface_cache/xet ✓
  Assets cache    : /Volumes/Amirali/hidden_states/huggingface_cache/assets ✓

→ Preparing Hugging Face model: HuggingFaceTB/SmolLM2-135M
  Pinned revision      : 93efa2f097d58c2a74874c7e644dbc9b0cee75a2
  Preparation attempt 1/4
  DOWNLOAD DIAGNOSTICS
    Revision             : 93efa2f097d58c2a74874c7e644dbc9b0cee75a2
    Cache                : /Volumes/Amirali/hidden_states/huggingface_cache/hub
    Workers              : 4
    ETag timeout         : 20.0s
    Allow patterns       : ['config.json', 'generation_config.json', 'tokenizer_config.json', 'tokenizer.json', 'special_tokens_map.json', 'added_tokens.json', 'vocab.json', 'merges.txt', 'spiece.model', 'spm.model', 'sentencepiece.bpe.model', 'tokenizer.model', 'vocab.txt', 'LICENSE*', 'README.md', '*.json', '*.safetensors']
    Ignore patterns      : ['*.h5', '*.msgpack', '*.ot', 'tf_model.*', 'flax_model.*', 'rust_model.ot', '*.onnx', '*.gguf', '*.ggml', '*.bin']

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

  ✓ Snapshot ready
    Attempt time        : 0.59s
    Total preparation   : 0.59s
    Checkpoint size     : 0.251 GiB
    Snapshot            : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--HuggingFaceTB--SmolLM2-135M/snapshots/93efa2f097d58c2a74874c7e644dbc9b0cee75a2

────────────────────────────────────────────────────────────────────────────────────────
MODEL PREFLIGHT
────────────────────────────────────────────────────────────────────────────────────────
  model                             : HuggingFaceTB/SmolLM2-135M
  model_type                        : llama
  architecture                      : decoder
  dtype                             : torch.float32
  device                            : cpu
  layers                            : 30
  hidden_size                       : 576
  hidden_states                     : 31
  max_length                        : 512
  checkpoint                        : {'active_bytes': 269064648, 'active_gb': 0.25058598071336746, 'inventory': {'safetensors': [{'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--HuggingFaceTB--SmolLM2-135M/snapshots/93efa2f097d58c2a74874c7e644dbc9b0cee75a2/._model.safetensors', 'filename': '._model.safetensors', 'size_bytes': 4096, 'size_gb': 3.814697265625e-06}, {'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--HuggingFaceTB--SmolLM2-135M/snapshots/93efa2f097d58c2a74874c7e644dbc9b0cee75a2/model.safetensors', 'filename': 'model.safetensors', 'size_bytes': 269060552, 'size_gb': 0.25058216601610184}], 'pytorch_bin': [], 'index_files': [], 'safetensors_total_bytes': 269064648, 'pytorch_bin_total_bytes': 0}}
  estimated_loaded_weight_gb        : 0.5011719614267349
  estimated_model_load_peak_gb      : 0.6014063537120818
  memory                            : {'total_gb': 8.0, 'available_gb': 2.6581077575683594, 'used_gb': 4.552768707275391, 'reserve_gb': 0.5316215515136719, 'safe_total_memory_gb': 6.4}
  status                            : ok
  ✓ Tokenizer loaded in 0.17s Mode=fast
  TOKENIZER DIAGNOSTICS
    class              : GPT2TokenizerFast
    vocab size         : 49152
    pad token          : '<|endoftext|>'
    pad source         : eos
    attempts           : [{"mode": "auto_fast", "success": true, "error_type": null, "error": null}]

MODEL LOAD ATTEMPT
  Attempt              : 1/2
  Path                 : primary
  Model                : HuggingFaceTB/SmolLM2-135M
  Snapshot             : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--HuggingFaceTB--SmolLM2-135M/snapshots/93efa2f097d58c2a74874c7e644dbc9b0cee75a2
  dtype                : torch.float32
  device               : cpu
  SDPA                 : True
  low_cpu_mem_usage    : True
  LOADING RESULT
    Missing keys        : 0
    Non-core missing    : 0
    Core missing        : 0
    Unexpected keys     : 0
    Mismatched keys     : 0
    Meta tensors        : 0
    Core meta           : 0
    Fatal discrepancy   : False
  FULL LOADING DIAGNOSTICS
{
  "missing_keys": [],
  "unexpected_keys": [],
  "mismatched_keys": [],
  "non_core_missing_keys": [],
  "core_missing_keys": [],
  "all_meta_tensors": [],
  "non_core_meta_tensors": [],
  "core_meta_tensors": [],
  "has_meta_tensors": false,
  "fatal": false
}

✓ MODEL READY
  Load/probe time       : 5.52s
  Backend               : sdpa
  Model device          : cpu
  Hidden states         : 31
  Hidden size           : 576
  Text-column resolver: exact candidate 'clean_text'

────────────────────────────────────────────────────────────────────────────────────────
DATASET goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Text column         : clean_text
  Samples             : 54,263
  Dataset fingerprint : 6302b3ba58f9886999c7
  Hidden layers       : 31
  Hidden size         : 576
  Output size est.    : 3.61 GiB
  Pooling             : mean
  Max length          : 512
  FROZEN batch        : 64
  Device              : cpu
  Runtime diagnostics : /Volumes/Amirali/hidden_states/experiments/baseline_v5_001/models/HuggingFaceTB/SmolLM2-135M/datasets/goEmo/metadata/runtime_state.json
  Existing progress   : 25,344/54,263 (46.71%)

goEmo:  47%|####6     | 25344/54263 [00:00<?, ?sample/s]

[start] starting at absolute sample 25344
[batch] 25344:25408 processed
[batch] 25408:25472 processed
[batch] 25472:25536 processed
[batch] 25536:25600 processed
[batch] 25600:25664 processed
[batch] 25664:25728 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 25,728/54,263 (47.41%)
  Newly computed       : 384
  Wall time            : 18.84s
  Throughput           : 20.39 samples/s
  ETA                  : 23m 19.7s
  Current stage        : measurement

  LAST BATCH
    Range              : 25664:25728
    New samples        : 64
    Total              : 3.84s
    Forward            : 3.34s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.04s
    Conversion         : 0.00s
    Memmap write       : 0.17s
    Flush              : 0.15s
    Sequence length    : 32
    Tokens             : 924
    Token throughput   : 240.74 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 3.124s
    Median batch       : 3.036s
    P95 batch          : 3.838s
    Max batch          : 3.838s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.67 GiB
    Process RSS        : 1.0590934753417969
    Peak RSS           : 1.06 GiB
    Minimum RAM        : 2.67 GiB
    External free      : 1750.41 GiB
    Successful batches : 6
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 25728:25792 processed
[batch] 25792:25856 processed
[batch] 25856:25920 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 25,920/54,263 (47.77%)
  Newly computed       : 576
  Wall time            : 37.43s
  Throughput           : 15.39 samples/s
  ETA                  : 30m 41.7s
  Current stage        : measurement

  LAST BATCH
    Range              : 25856:25920
    New samples        : 64
    Total              : 6.27s
    Forward            : 5.52s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.07s
    Conversion         : 0.00s
    Memmap write       : 0.21s
    Flush              : 0.14s
    Sequence length    : 31
    Tokens             : 1042
    Token throughput   : 166.22 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 4.143s
    Median batch       : 3.259s
    P95 batch          : 6.403s
    Max batch          : 6.403s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.53 GiB
    Process RSS        : 1.0681724548339844
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.53 GiB
    External free      : 1750.41 GiB
    Successful batches : 9
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 25920:25984 processed
[batch] 25984:26048 processed
[batch] 26048:26112 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 26,112/54,263 (48.12%)
  Newly computed       : 768
  Wall time            : 54.18s
  Throughput           : 14.18 samples/s
  ETA                  : 33m 05.9s
  Current stage        : measurement

  LAST BATCH
    Range              : 26048:26112
    New samples        : 64
    Total              : 5.71s
    Forward            : 5.02s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.19s
    Conversion         : 0.00s
    Memmap write       : 0.12s
    Flush              : 0.12s
    Sequence length    : 36
    Tokens             : 1066
    Token throughput   : 186.65 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 4.500s
    Median batch       : 4.661s
    P95 batch          : 6.403s
    Max batch          : 6.403s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.91 GiB
    Process RSS        : 1.003448486328125
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.53 GiB
    External free      : 1750.41 GiB
    Successful batches : 12
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 26112:26176 processed
[batch] 26176:26240 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 26,240/54,263 (48.36%)
  Newly computed       : 896
  Wall time            : 1m 11.9s
  Throughput           : 12.47 samples/s
  ETA                  : 37m 27.9s
  Current stage        : measurement

  LAST BATCH
    Range              : 26176:26240
    New samples        : 64
    Total              : 5.85s
    Forward            : 5.26s
    Tokenization       : 0.02s
    Input transfer     : 0.00s
    Pooling            : 0.06s
    Conversion         : 0.00s
    Memmap write       : 0.19s
    Flush              : 0.13s
    Sequence length    : 32
    Tokens             : 976
    Token throughput   : 166.80 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 5.118s
    Median batch       : 5.497s
    P95 batch          : 11.804s
    Max batch          : 11.804s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.87 GiB
    Process RSS        : 0.7463150024414062
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.53 GiB
    External free      : 1750.41 GiB
    Successful batches : 14
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 26240:26304 processed
[batch] 26304:26368 processed
[batch] 26368:26432 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 26,432/54,263 (48.71%)
  Newly computed       : 1,088
  Wall time            : 1m 28.9s
  Throughput           : 12.23 samples/s
  ETA                  : 37m 55.2s
  Current stage        : measurement

  LAST BATCH
    Range              : 26368:26432
    New samples        : 64
    Total              : 5.49s
    Forward            : 4.94s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.05s
    Conversion         : 0.00s
    Memmap write       : 0.17s
    Flush              : 0.13s
    Sequence length    : 32
    Tokens             : 1076
    Token throughput   : 195.98 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 5.215s
    Median batch       : 5.510s
    P95 batch          : 11.804s
    Max batch          : 11.804s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.73 GiB
    Process RSS        : 0.7299957275390625
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.53 GiB
    External free      : 1750.41 GiB
    Successful batches : 17
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 26432:26496 processed
[batch] 26496:26560 processed
[batch] 26560:26624 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 26,624/54,263 (49.06%)
  Newly computed       : 1,280
  Wall time            : 1m 47.3s
  Throughput           : 11.93 samples/s
  ETA                  : 38m 37.1s
  Current stage        : measurement

  LAST BATCH
    Range              : 26560:26624
    New samples        : 64
    Total              : 7.41s
    Forward            : 6.70s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.11s
    Conversion         : 0.00s
    Memmap write       : 0.19s
    Flush              : 0.15s
    Sequence length    : 39
    Tokens             : 1046
    Token throughput   : 141.12 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 5.349s
    Median batch       : 5.544s
    P95 batch          : 7.412s
    Max batch          : 11.804s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.85 GiB
    Process RSS        : 0.7764015197753906
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.53 GiB
    External free      : 1750.41 GiB
    Successful batches : 20
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 26624:26688 processed
[batch] 26688:26752 processed
[batch] 26752:26816 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 26,816/54,263 (49.42%)
  Newly computed       : 1,472
  Wall time            : 2m 06.3s
  Throughput           : 11.65 samples/s
  ETA                  : 39m 15.5s
  Current stage        : measurement

  LAST BATCH
    Range              : 26752:26816
    New samples        : 64
    Total              : 5.30s
    Forward            : 4.84s
    Tokenization       : 0.02s
    Input transfer     : 0.00s
    Pooling            : 0.04s
    Conversion         : 0.00s
    Memmap write       : 0.16s
    Flush              : 0.12s
    Sequence length    : 32
    Tokens             : 1033
    Token throughput   : 194.87 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 5.871s
    Median batch       : 5.663s
    P95 batch          : 7.412s
    Max batch          : 11.804s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.82 GiB
    Process RSS        : 0.7644729614257812
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.53 GiB
    External free      : 1750.41 GiB
    Successful batches : 23
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 26816:26880 processed
[batch] 26880:26944 processed
[batch] 26944:27008 processed
[batch] 27008:27072 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 27,072/54,263 (49.89%)
  Newly computed       : 1,728
  Wall time            : 2m 21.5s
  Throughput           : 12.22 samples/s
  ETA                  : 37m 06.0s
  Current stage        : measurement

  LAST BATCH
    Range              : 27008:27072
    New samples        : 64
    Total              : 3.57s
    Forward            : 3.11s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.03s
    Conversion         : 0.00s
    Memmap write       : 0.16s
    Flush              : 0.11s
    Sequence length    : 32
    Tokens             : 954
    Token throughput   : 267.57 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 5.796s
    Median batch       : 5.596s
    P95 batch          : 7.412s
    Max batch          : 11.804s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.81 GiB
    Process RSS        : 0.7836494445800781
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.53 GiB
    External free      : 1750.41 GiB
    Successful batches : 27
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 27072:27136 processed
[batch] 27136:27200 processed
[batch] 27200:27264 processed
[batch] 27264:27328 processed
[batch] 27328:27392 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 27,392/54,263 (50.48%)
  Newly computed       : 2,048
  Wall time            : 2m 39.5s
  Throughput           : 12.84 samples/s
  ETA                  : 34m 52.5s
  Current stage        : measurement

  LAST BATCH
    Range              : 27328:27392
    New samples        : 64
    Total              : 4.18s
    Forward            : 3.66s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.05s
    Conversion         : 0.00s
    Memmap write       : 0.15s
    Flush              : 0.15s
    Sequence length    : 33
    Tokens             : 962
    Token throughput   : 229.95 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 5.254s
    Median batch       : 5.313s
    P95 batch          : 7.412s
    Max batch          : 11.804s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.81 GiB
    Process RSS        : 0.8159523010253906
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.53 GiB
    External free      : 1750.41 GiB
    Successful batches : 32
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 27392:27456 processed
[batch] 27456:27520 processed
[batch] 27520:27584 processed
[batch] 27584:27648 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 27,648/54,263 (50.95%)
  Newly computed       : 2,304
  Wall time            : 3m 01.1s
  Throughput           : 12.72 samples/s
  ETA                  : 34m 52.5s
  Current stage        : measurement

  LAST BATCH
    Range              : 27584:27648
    New samples        : 64
    Total              : 7.32s
    Forward            : 6.69s
    Tokenization       : 0.02s
    Input transfer     : 0.00s
    Pooling            : 0.07s
    Conversion         : 0.00s
    Memmap write       : 0.15s
    Flush              : 0.12s
    Sequence length    : 54
    Tokens             : 1087
    Token throughput   : 148.41 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 4.876s
    Median batch       : 4.583s
    P95 batch          : 7.324s
    Max batch          : 7.412s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.62 GiB
    Process RSS        : 0.9258193969726562
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.53 GiB
    External free      : 1750.40 GiB
    Successful batches : 36
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 27648:27712 processed
[batch] 27712:27776 processed
[batch] 27776:27840 processed
[batch] 27840:27904 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 27,904/54,263 (51.42%)
  Newly computed       : 2,560
  Wall time            : 3m 19.3s
  Throughput           : 12.85 samples/s
  ETA                  : 34m 11.7s
  Current stage        : measurement

  LAST BATCH
    Range              : 27840:27904
    New samples        : 64
    Total              : 4.56s
    Forward            : 4.07s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.05s
    Conversion         : 0.00s
    Memmap write       : 0.14s
    Flush              : 0.13s
    Sequence length    : 34
    Tokens             : 1107
    Token throughput   : 242.91 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 4.590s
    Median batch       : 4.147s
    P95 batch          : 6.938s
    Max batch          : 7.324s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.62 GiB
    Process RSS        : 0.8619270324707031
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.53 GiB
    External free      : 1750.40 GiB
    Successful batches : 40
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 27904:27968 processed
[batch] 27968:28032 processed
[batch] 28032:28096 processed
[batch] 28096:28160 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 28,160/54,263 (51.90%)
  Newly computed       : 2,816
  Wall time            : 3m 35.5s
  Throughput           : 13.07 samples/s
  ETA                  : 33m 17.6s
  Current stage        : measurement

  LAST BATCH
    Range              : 28096:28160
    New samples        : 64
    Total              : 3.70s
    Forward            : 3.21s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.04s
    Conversion         : 0.00s
    Memmap write       : 0.15s
    Flush              : 0.13s
    Sequence length    : 34
    Tokens             : 944
    Token throughput   : 255.19 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 4.268s
    Median batch       : 4.097s
    P95 batch          : 5.221s
    Max batch          : 7.324s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.64 GiB
    Process RSS        : 0.8737144470214844
    Peak RSS           : 1.07 GiB
    Minimum RAM        : 2.53 GiB
    External free      : 1750.40 GiB
    Successful batches : 44
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 28160:28224 processed
[batch] 28224:28288 processed
[batch] 28288:28352 processed
[batch] 28352:28416 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 28,416/54,263 (52.37%)
  Newly computed       : 3,072
  Wall time            : 3m 51.2s
  Throughput           : 13.28 samples/s
  ETA                  : 32m 25.7s
  Current stage        : measurement

  LAST BATCH
    Range              : 28352:28416
    New samples        : 64
    Total              : 4.06s
    Forward            : 3.57s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.05s
    Conversion         : 0.00s
    Memmap write       : 0.15s
    Flush              : 0.14s
    Sequence length    : 33
    Tokens             : 1116
    Token throughput   : 275.20 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 4.330s
    Median batch       : 4.097s
    P95 batch          : 5.221s
    Max batch          : 7.324s
    Slow batches       : 0

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

  ✓ Snapshot ready
    Attempt time        : 1.75s
    Total preparation   : 1.76s
    Checkpoint size     : 0.920 GiB
    Snapshot            : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--Qwen--Qwen2-0.5B/snapshots/91d2aff3f957f99e4c74c962f2f408dcc88a18d8

────────────────────────────────────────────────────────────────────────────────────────
MODEL PREFLIGHT
────────────────────────────────────────────────────────────────────────────────────────
  model                             : Qwen/Qwen2-0.5B
  model_type                        : qwen2
  architecture                      : decoder
  dtype                             : torch.float32
  device                            : cpu
  layers                            : 24
  hidden_size                       : 896
  hidden_states                     : 25
  max_length                        : 512
  checkpoint                        : {'active_bytes': 988097824, 'active_gb': 0.920237809419632, 'inventory': {'safetensors': [{'path': '/Volumes/Amirali/hidden_states/huggingface_cache/hub/models--Qwen--Qwen2-0.5B/snapshots/91d2aff3f957f99e4c74c962f2f408dcc88a18d8/model.safetensors', 'filename': 'model.safetensors', 'size_bytes': 988097824, 'size_gb': 0.920237809419632}], 'pytorch_bin': [], 'index_files': [], 'safetensors_total_bytes': 988097824, 'pytorch_bin_total_bytes': 0}}
  estimated_loaded_weight_gb        : 1.840475618839264
  estimated_model_load_peak_gb      : 2.2085707426071166
  memory                            : {'total_gb': 8.0, 'available_gb': 2.3893775939941406, 'used_gb': 4.5131072998046875, 'reserve_gb': 0.5, 'safe_total_memory_gb': 6.4}
  status                            : ok
  ✓ Tokenizer loaded in 0.64s Mode=fast
  TOKENIZER DIAGNOSTICS
    class              : Qwen2TokenizerFast
    vocab size         : 151646
    pad token          : '<|endoftext|>'
    pad source         : checkpoint-defined
    attempts           : [{"mode": "auto_fast", "success": true, "error_type": null, "error": null}]

MODEL LOAD ATTEMPT
  Attempt              : 1/2
  Path                 : primary
  Model                : Qwen/Qwen2-0.5B
  Snapshot             : /Volumes/Amirali/hidden_states/huggingface_cache/hub/models--Qwen--Qwen2-0.5B/snapshots/91d2aff3f957f99e4c74c962f2f408dcc88a18d8
  dtype                : torch.float32
  device               : cpu
  SDPA                 : True
  low_cpu_mem_usage    : True
  LOADING RESULT
    Missing keys        : 0
    Non-core missing    : 0
    Core missing        : 0
    Unexpected keys     : 0
    Mismatched keys     : 0
    Meta tensors        : 0
    Core meta           : 0
    Fatal discrepancy   : False
  FULL LOADING DIAGNOSTICS
{
  "missing_keys": [],
  "unexpected_keys": [],
  "mismatched_keys": [],
  "non_core_missing_keys": [],
  "core_missing_keys": [],
  "all_meta_tensors": [],
  "non_core_meta_tensors": [],
  "core_meta_tensors": [],
  "has_meta_tensors": false,
  "fatal": false
}

✓ MODEL READY
  Load/probe time       : 22.92s
  Backend               : sdpa
  Model device          : cpu
  Hidden states         : 25
  Hidden size           : 896
  Text-column resolver: exact candidate 'clean_text'

────────────────────────────────────────────────────────────────────────────────────────
DATASET goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Text column         : clean_text
  Samples             : 54,263
  Dataset fingerprint : 6302b3ba58f9886999c7
  Hidden layers       : 25
  Hidden size         : 896
  Output size est.    : 4.53 GiB
  Pooling             : mean
  Max length          : 512
  FROZEN batch        : 32
  Device              : cpu
  Runtime diagnostics : /Volumes/Amirali/hidden_states/experiments/baseline_v5_001/models/Qwen/Qwen2-0.5B/datasets/goEmo/metadata/runtime_state.json
  Existing progress   : 32/54,263 (0.06%)

goEmo:   0%|          | 32/54263 [00:00<?, ?sample/s]

[start] starting at absolute sample 32
[batch] 32:64 processed
[batch] 64:96 processed
[batch] 96:128 processed
[batch] 128:160 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 160/54,263 (0.29%)
  Newly computed       : 128
  Wall time            : 15.34s
  Throughput           : 8.34 samples/s
  ETA                  : 1h 48m 05.1s
  Current stage        : measurement

  LAST BATCH
    Range              : 128:160
    New samples        : 32
    Total              : 3.81s
    Forward            : 3.51s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.02s
    Conversion         : 0.00s
    Memmap write       : 0.13s
    Flush              : 0.06s
    Sequence length    : 33
    Tokens             : 513
    Token throughput   : 134.47 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 3.805s
    Median batch       : 3.882s
    P95 batch          : 4.049s
    Max batch          : 4.049s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.32 GiB
    Process RSS        : 1.7852554321289062
    Peak RSS           : 1.79 GiB
    Minimum RAM        : 2.32 GiB
    External free      : 1749.85 GiB
    Successful batches : 4
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 160:192 processed
[batch] 192:224 processed
[batch] 224:256 processed
[batch] 256:288 processed
[batch] 288:320 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 320/54,263 (0.59%)
  Newly computed       : 288
  Wall time            : 34.47s
  Throughput           : 8.35 samples/s
  ETA                  : 1h 47m 36.8s
  Current stage        : measurement

  LAST BATCH
    Range              : 288:320
    New samples        : 32
    Total              : 4.99s
    Forward            : 4.56s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.05s
    Conversion         : 0.00s
    Memmap write       : 0.15s
    Flush              : 0.06s
    Sequence length    : 35
    Tokens             : 541
    Token throughput   : 108.51 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 3.810s
    Median batch       : 3.769s
    P95 batch          : 4.986s
    Max batch          : 4.986s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.30 GiB
    Process RSS        : 1.8092231750488281
    Peak RSS           : 1.81 GiB
    Minimum RAM        : 2.30 GiB
    External free      : 1749.85 GiB
    Successful batches : 9
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 320:352 processed
[batch] 352:384 processed
[batch] 384:416 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 416/54,263 (0.77%)
  Newly computed       : 384
  Wall time            : 52.57s
  Throughput           : 7.30 samples/s
  ETA                  : 2h 2m 52.4s
  Current stage        : measurement

  LAST BATCH
    Range              : 384:416
    New samples        : 32
    Total              : 5.70s
    Forward            : 5.37s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.02s
    Conversion         : 0.00s
    Memmap write       : 0.13s
    Flush              : 0.07s
    Sequence length    : 32
    Tokens             : 438
    Token throughput   : 76.87 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 4.362s
    Median batch       : 3.882s
    P95 batch          : 7.012s
    Max batch          : 7.012s
    Slow batches       : 0
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.27 GiB
    Process RSS        : 1.6501541137695312
    Peak RSS           : 1.81 GiB
    Minimum RAM        : 2.27 GiB
    External free      : 1749.85 GiB
    Successful batches : 12
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 416:448 processed
[batch] 448:480 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 480/54,263 (0.88%)
  Newly computed       : 448
  Wall time            : 1m 20.0s
  Throughput           : 5.60 samples/s
  ETA                  : 2h 40m 09.9s
  Current stage        : measurement

  LAST BATCH
    Range              : 448:480
    New samples        : 32
    Total              : 18.55s
    Forward            : 17.42s
    Tokenization       : 0.03s
    Input transfer     : 0.00s
    Pooling            : 0.14s
    Conversion         : 0.00s
    Memmap write       : 0.15s
    Flush              : 0.11s
    Sequence length    : 41
    Tokens             : 475
    Token throughput   : 25.61 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 5.694s
    Median batch       : 4.000s
    P95 batch          : 18.550s
    Max batch          : 18.550s
    Slow batches       : 1
    Current anomaly    : YES (x4.64)

  MEMORY / STORAGE
    RAM available      : 1.69 GiB
    Process RSS        : 0.6528472900390625
    Peak RSS           : 1.81 GiB
    Minimum RAM        : 1.69 GiB
    External free      : 1749.85 GiB
    Successful batches : 14
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 480:512 processed
[batch] 512:544 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 544/54,263 (1.00%)
  Newly computed       : 512
  Wall time            : 1m 37.9s
  Throughput           : 5.23 samples/s
  ETA                  : 2h 51m 15.5s
  Current stage        : measurement

  LAST BATCH
    Range              : 512:544
    New samples        : 32
    Total              : 7.13s
    Forward            : 6.75s
    Tokenization       : 0.02s
    Input transfer     : 0.00s
    Pooling            : 0.05s
    Conversion         : 0.00s
    Memmap write       : 0.16s
    Flush              : 0.04s
    Sequence length    : 30
    Tokens             : 475
    Token throughput   : 66.60 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 6.097s
    Median batch       : 4.517s
    P95 batch          : 18.550s
    Max batch          : 18.550s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.64 GiB
    Process RSS        : 1.5699462890625
    Peak RSS           : 1.81 GiB
    Minimum RAM        : 1.69 GiB
    External free      : 1749.85 GiB
    Successful batches : 16
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 544:576 processed
[batch] 576:608 processed
[batch] 608:640 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 640/54,263 (1.18%)
  Newly computed       : 608
  Wall time            : 2m 00.4s
  Throughput           : 5.05 samples/s
  ETA                  : 2h 57m 01.5s
  Current stage        : measurement

  LAST BATCH
    Range              : 608:640
    New samples        : 32
    Total              : 7.68s
    Forward            : 7.23s
    Tokenization       : 0.04s
    Input transfer     : 0.00s
    Pooling            : 0.05s
    Conversion         : 0.00s
    Memmap write       : 0.09s
    Flush              : 0.08s
    Sequence length    : 31
    Tokens             : 582
    Token throughput   : 75.73 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 6.315s
    Median batch       : 5.346s
    P95 batch          : 18.550s
    Max batch          : 18.550s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.67 GiB
    Process RSS        : 1.5008049011230469
    Peak RSS           : 1.81 GiB
    Minimum RAM        : 1.69 GiB
    External free      : 1749.85 GiB
    Successful batches : 19
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 640:672 processed
[batch] 672:704 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 704/54,263 (1.30%)
  Newly computed       : 672
  Wall time            : 2m 16.0s
  Throughput           : 4.94 samples/s
  ETA                  : 3h 0m 38.0s
  Current stage        : measurement

  LAST BATCH
    Range              : 672:704
    New samples        : 32
    Total              : 7.88s
    Forward            : 7.43s
    Tokenization       : 0.03s
    Input transfer     : 0.00s
    Pooling            : 0.05s
    Conversion         : 0.00s
    Memmap write       : 0.09s
    Flush              : 0.07s
    Sequence length    : 32
    Tokens             : 522
    Token throughput   : 66.23 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 6.575s
    Median batch       : 6.345s
    P95 batch          : 10.698s
    Max batch          : 18.550s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.89 GiB
    Process RSS        : 1.5948715209960938
    Peak RSS           : 1.81 GiB
    Minimum RAM        : 1.69 GiB
    External free      : 1749.85 GiB
    Successful batches : 21
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 704:736 processed
[batch] 736:768 processed
[batch] 768:800 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 800/54,263 (1.47%)
  Newly computed       : 768
  Wall time            : 2m 34.9s
  Throughput           : 4.96 samples/s
  ETA                  : 2h 59m 45.8s
  Current stage        : measurement

  LAST BATCH
    Range              : 768:800
    New samples        : 32
    Total              : 6.22s
    Forward            : 5.76s
    Tokenization       : 0.04s
    Input transfer     : 0.00s
    Pooling            : 0.03s
    Conversion         : 0.00s
    Memmap write       : 0.16s
    Flush              : 0.05s
    Sequence length    : 34
    Tokens             : 559
    Token throughput   : 89.82 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 6.955s
    Median batch       : 6.897s
    P95 batch          : 10.698s
    Max batch          : 18.550s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.82 GiB
    Process RSS        : 1.6107292175292969
    Peak RSS           : 1.81 GiB
    Minimum RAM        : 1.69 GiB
    External free      : 1749.85 GiB
    Successful batches : 24
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 800:832 processed
[batch] 832:864 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 864/54,263 (1.59%)
  Newly computed       : 832
  Wall time            : 2m 53.0s
  Throughput           : 4.81 samples/s
  ETA                  : 3h 5m 05.3s
  Current stage        : measurement

  LAST BATCH
    Range              : 832:864
    New samples        : 32
    Total              : 8.04s
    Forward            : 7.47s
    Tokenization       : 0.03s
    Input transfer     : 0.00s
    Pooling            : 0.05s
    Conversion         : 0.00s
    Memmap write       : 0.15s
    Flush              : 0.12s
    Sequence length    : 33
    Tokens             : 432
    Token throughput   : 53.75 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 7.524s
    Median batch       : 7.072s
    P95 batch          : 10.698s
    Max batch          : 18.550s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.43 GiB
    Process RSS        : 1.6084022521972656
    Peak RSS           : 1.81 GiB
    Minimum RAM        : 1.69 GiB
    External free      : 1749.85 GiB
    Successful batches : 26
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 864:896 processed
[batch] 896:928 processed
[batch] 928:960 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 960/54,263 (1.77%)
  Newly computed       : 928
  Wall time            : 3m 12.2s
  Throughput           : 4.83 samples/s
  ETA                  : 3h 3m 59.4s
  Current stage        : measurement

  LAST BATCH
    Range              : 928:960
    New samples        : 32
    Total              : 5.17s
    Forward            : 4.84s
    Tokenization       : 0.03s
    Input transfer     : 0.00s
    Pooling            : 0.03s
    Conversion         : 0.00s
    Memmap write       : 0.09s
    Flush              : 0.06s
    Sequence length    : 29
    Tokens             : 528
    Token throughput   : 102.21 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 7.857s
    Median batch       : 7.356s
    P95 batch          : 10.698s
    Max batch          : 18.550s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.65 GiB
    Process RSS        : 1.61041259765625
    Peak RSS           : 1.81 GiB
    Minimum RAM        : 1.69 GiB
    External free      : 1749.85 GiB
    Successful batches : 29
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 960:992 processed
[batch] 992:1024 processed
[batch] 1024:1056 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 1,056/54,263 (1.95%)
  Newly computed       : 1,024
  Wall time            : 3m 27.3s
  Throughput           : 4.94 samples/s
  ETA                  : 2h 59m 32.4s
  Current stage        : measurement

  LAST BATCH
    Range              : 1024:1056
    New samples        : 32
    Total              : 4.69s
    Forward            : 4.32s
    Tokenization       : 0.03s
    Input transfer     : 0.00s
    Pooling            : 0.04s
    Conversion         : 0.00s
    Memmap write       : 0.15s
    Flush              : 0.03s
    Sequence length    : 30
    Tokens             : 441
    Token throughput   : 93.98 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 7.709s
    Median batch       : 7.356s
    P95 batch          : 10.698s
    Max batch          : 18.550s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.70 GiB
    Process RSS        : 1.6248626708984375
    Peak RSS           : 1.81 GiB
    Minimum RAM        : 1.69 GiB
    External free      : 1749.85 GiB
    Successful batches : 32
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 1056:1088 processed
[batch] 1088:1120 processed
[batch] 1120:1152 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 1,152/54,263 (2.12%)
  Newly computed       : 1,120
  Wall time            : 3m 43.3s
  Throughput           : 5.02 samples/s
  ETA                  : 2h 56m 28.5s
  Current stage        : measurement

  LAST BATCH
    Range              : 1120:1152
    New samples        : 32
    Total              : 6.14s
    Forward            : 5.74s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.05s
    Conversion         : 0.00s
    Memmap write       : 0.15s
    Flush              : 0.04s
    Sequence length    : 41
    Tokens             : 529
    Token throughput   : 86.16 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 6.601s
    Median batch       : 6.536s
    P95 batch          : 8.037s
    Max batch          : 9.997s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.74 GiB
    Process RSS        : 1.6657905578613281
    Peak RSS           : 1.81 GiB
    Minimum RAM        : 1.69 GiB
    External free      : 1749.85 GiB
    Successful batches : 35
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 1152:1184 processed
[batch] 1184:1216 processed
[batch] 1216:1248 processed
[batch] 1248:1280 processed

────────────────────────────────────────────────────────────────────────────────────────
RUNTIME / SPEED TELEMETRY :: goEmo
────────────────────────────────────────────────────────────────────────────────────────
  Progress             : 1,280/54,263 (2.36%)
  Newly computed       : 1,248
  Wall time            : 4m 02.5s
  Throughput           : 5.15 samples/s
  ETA                  : 2h 51m 35.8s
  Current stage        : measurement

  LAST BATCH
    Range              : 1248:1280
    New samples        : 32
    Total              : 4.82s
    Forward            : 4.51s
    Tokenization       : 0.01s
    Input transfer     : 0.00s
    Pooling            : 0.03s
    Conversion         : 0.00s
    Memmap write       : 0.09s
    Flush              : 0.06s
    Sequence length    : 32
    Tokens             : 436
    Token throughput   : 90.46 tokens/s

  ROLLING PERFORMANCE
    Mean batch         : 6.082s
    Median batch       : 5.548s
    P95 batch          : 8.037s
    Max batch          : 9.997s
    Slow batches       : 1
    Current anomaly    : NO

  MEMORY / STORAGE
    RAM available      : 2.67 GiB
    Process RSS        : 1.6562995910644531
    Peak RSS           : 1.81 GiB
    Minimum RAM        : 1.69 GiB
    External free      : 1749.85 GiB
    Successful batches : 39
    Debug batch output : ON
────────────────────────────────────────────────────────────────────────────────────────
[runtime] periodic runtime telemetry
[batch] 1280:1312 processed
[batch] 1312:1344 processed
[batch] 1344:1376 processed

KeyboardInterrupt:

In [ ]:
# =============================================================================
# CELL 4 – COLLECT ALL RESULTS FROM DISK (PARTIAL INCLUDED)
# =============================================================================

exp_root = Path("/Volumes/Amirali/hidden_states/experiments/baseline_v5_001")
df_results = load_experiment_results(exp_root)

if not df_results.empty:
    display_title("Extraction Progress")
    display(df_results[['model', 'dataset', 'status', 'completed_samples', 'total_samples']].head(15))
    display_info(f"Total dataset‑model pairs found: <b>{len(df_results)}</b>")
else:
    display_info("No extraction metadata found yet. Run the extraction first (Cell 3).")

In [ ]:
# =============================================================================
# CELL 5 – VISUALISATIONS & ANALYSIS
# =============================================================================

if not df_results.empty:
    # Prepare data for plotting
    df = df_results.copy()
    df['completion_pct'] = df['completed_samples'] / df['total_samples'] * 100
    df['status_clean'] = df['status'].replace({'complete': 'Complete', 'partial': 'Partial', 'failed': 'Failed', 'already_complete': 'Already Complete'})

    sns.set_style("darkgrid")
    plt.rcParams.update({
        'figure.facecolor': '#1e1e1e',
        'axes.facecolor': '#2d2d2d',
        'axes.edgecolor': '#d4d4d4',
        'axes.labelcolor': '#d4d4d4',
        'text.color': '#d4d4d4',
        'xtick.color': '#d4d4d4',
        'ytick.color': '#d4d4d4',
        'grid.color': '#444444',
        'legend.facecolor': '#2d2d2d',
        'legend.edgecolor': '#d4d4d4',
    })

    # ---- 1. Completion status per model/dataset ----
    fig, ax = plt.subplots(figsize=(12, 8))
    pivot = df.pivot_table(index='model', columns='dataset', values='completion_pct', aggfunc='max')
    sns.heatmap(pivot, annot=True, fmt=".0f", cmap="viridis", cbar_kws={'label': 'Completion %'}, ax=ax)
    ax.set_title('Completion Percentage by Model and Dataset', color='#4fc3f7')
    plt.tight_layout()
    plt.show()

    # ---- 2. Throughput (samples/sec) by model ----
    df_complete = df[df['samples_per_second'].notna()]
    if not df_complete.empty:
        fig, ax = plt.subplots(figsize=(14, 6))
        sns.barplot(data=df_complete, x='model', y='samples_per_second', hue='dataset', palette='coolwarm', ax=ax)
        ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
        ax.set_title('Extraction Throughput (samples/sec)', color='#4fc3f7')
        plt.tight_layout()
        plt.show()

    # ---- 3. Total time per model ----
    df_time = df.groupby('model')['elapsed_seconds'].sum().reset_index().sort_values('elapsed_seconds', ascending=False)
    fig, ax = plt.subplots(figsize=(12, 6))
    sns.barplot(data=df_time, x='elapsed_seconds', y='model', palette='magma', ax=ax)
    ax.set_xlabel('Total Elapsed Time (seconds)')
    ax.set_title('Cumulative Extraction Time per Model', color='#4fc3f7')
    plt.tight_layout()
    plt.show()

    # ---- 4. Label coverage for completed datasets ----
    # We'll just display label column info
    display_title("Label Columns Used")
    display(df[['model', 'dataset', 'label_column']].drop_duplicates())
else:
    display_info("No data to visualise. Please run extraction first.")

In [ ]:
# =============================================================================
# CELL 6 – FINAL SUMMARY & EXPORT
# =============================================================================

if not df_results.empty:
    # Save consolidated CSV
    output_csv = exp_root / "extraction_summary.csv"
    df_results.to_csv(output_csv, index=False)
    display_title("Final Report")
    display(df_results)
    display_info(f"Report exported to <code>{output_csv}</code>")
else:
    display_info("Nothing to export yet.")